import { CourseDefinition } from '../types';
import { AI_ACCURACY_GUIDELINES } from './guidelines';

export const ai: CourseDefinition = {
    id: 'ai',
    title: 'Artificial Intelligence Foundations',
    tagline: 'How machines search, reason, learn, and understand language, built from scratch in Python.',
    level: 'Beginner → Intermediate (basic Python)',
    hours: 40,
    accent: '#A855F7',
    badge: 'AI',
    requires: ['python'],
    category: 'ai',
    stack: 'Python',
    tutorGuidelines: [
        ...AI_ACCURACY_GUIDELINES,
        'Build small versions from scratch first (a search algorithm, naive Bayes, a single neuron) before showing the library equivalent, so the learner sees there is no magic.',
        'Keep the math intuitive and visual. Introduce a formula only after the idea is clear, and show it as working NumPy code.',
    ],
    modules: [
        {
            title: 'What AI Really Is',
            description: 'Cut through the hype: what AI is, what it is not, and how the field fits together.',
            lessons: [
                'Defining AI: intelligent agents and rational behavior',
                'Narrow AI vs general AI',
                'A short history: symbolic AI, machine learning, deep learning',
                'How AI, machine learning, deep learning, and data science relate',
                'Where AI is used today, and where it fails',
                'Setting up Python, a virtual environment, and NumPy',
            ],
        },
        {
            title: 'The Math You Actually Need',
            description: 'Just enough linear algebra, calculus, and probability, taught through code.',
            lessons: [
                'Vectors and matrices with NumPy',
                'Dot products and what they measure',
                'Derivatives and gradients as "which way is downhill"',
                'Probability basics: events, conditional probability',
                "Bayes' theorem with a worked example",
                'Mean, variance, and the normal distribution',
                'Exercise: implement vector and probability helpers',
            ],
        },
        {
            title: 'Problem Solving as Search',
            description: 'Classic AI: agents that find their way through a space of possibilities.',
            lessons: [
                'Agents, environments, states, and actions',
                'Modeling a problem as a state space',
                'Breadth-first search',
                'Depth-first search',
                'Uniform-cost search',
                'Heuristics and A* search',
                'Exercise: a maze-solving agent',
            ],
        },
        {
            title: 'Games & Adversarial Search',
            description: 'Teach a program to play against you and plan ahead.',
            lessons: [
                'Game trees and turn-based games',
                'The minimax algorithm',
                'Alpha-beta pruning',
                'Evaluation functions for large games',
                'Exercise: an unbeatable tic-tac-toe AI',
            ],
        },
        {
            title: 'Knowledge & Reasoning Under Uncertainty',
            description: 'Represent what an agent knows, and reason when the world is uncertain.',
            lessons: [
                'Propositional logic and knowledge bases',
                'Inference: deriving new facts from rules',
                'Rule-based expert systems and their limits',
                'Reasoning with probability',
                'Bayesian networks: the intuition',
                'Exercise: a naive Bayes spam filter from scratch',
            ],
        },
        {
            title: 'Machine Learning Fundamentals',
            description: 'Instead of writing rules, let the program learn them from data.',
            lessons: [
                'Supervised, unsupervised, and reinforcement learning',
                'Features, labels, and datasets',
                'Training and test sets: why we hold data back',
                'Linear regression',
                'Classification with logistic regression',
                'k-nearest neighbors',
                'Decision trees',
                'Evaluation metrics: accuracy, precision, recall',
                'Overfitting and underfitting',
                'Exercise: train and evaluate a classifier with scikit-learn',
            ],
        },
        {
            title: 'Neural Networks',
            description: 'From a single artificial neuron to a network that learns.',
            lessons: [
                'The perceptron',
                'Building a neuron from scratch in NumPy',
                'Activation functions: sigmoid, tanh, ReLU',
                'Layers and the forward pass',
                'Loss functions',
                'Gradient descent',
                'Backpropagation: the intuition',
                'Exercise: train a tiny network to learn XOR',
                'A first look at PyTorch tensors',
            ],
        },
        {
            title: 'Deep Learning Architectures',
            description: 'The ideas behind modern vision and language models.',
            lessons: [
                'Why deeper networks help, and what makes them hard to train',
                'Convolutional neural networks for images',
                'Recurrent networks for sequences',
                'The attention mechanism',
                'Transformers at a high level',
                'Transfer learning and pretrained models',
            ],
        },
        {
            title: 'Natural Language Processing & LLMs',
            description: 'How computers work with text, up to today\'s large language models.',
            lessons: [
                'Text preprocessing and tokenization',
                'Bag of words and TF-IDF',
                'Word embeddings: meaning as vectors',
                'Language models: predicting the next token',
                'How LLMs are trained: pretraining, fine-tuning, human feedback',
                'Prompting an LLM effectively',
                'Why LLMs hallucinate, and how to reduce it',
                'Calling an LLM API safely (keys in environment variables)',
            ],
        },
        {
            title: 'Reinforcement Learning',
            description: 'Agents that learn by trial, error, and reward.',
            lessons: [
                'Rewards, states, actions, and policies',
                'Exploration vs exploitation',
                'Multi-armed bandits',
                'Markov decision processes',
                'Q-learning',
                'Exercise: a Q-learning agent in a grid world',
            ],
        },
        {
            title: 'AI Ethics, Safety & Responsibility',
            description: 'Build AI that is fair, honest about its limits, and safe to deploy.',
            lessons: [
                'Bias in data and models',
                'Fairness: measuring and mitigating harm',
                'Privacy and responsible data use',
                'Explainability: why did the model decide that?',
                'AI safety and misuse',
                'A responsible deployment checklist',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'Take an AI project from idea to honest, evaluated result.',
            lessons: [
                'Choosing a problem and a dataset',
                'Building a simple baseline first',
                'Training and evaluating a model',
                'Error analysis: learning from mistakes',
                'Improving the model step by step',
                'Presenting results and limitations honestly',
            ],
        },
    ],
};
