import { Course } from '../types';

export const android: Course = {
    id: 'android',
    title: 'Android with Jetpack Compose',
    tagline: 'Build real Android apps in Kotlin with the modern UI toolkit.',
    level: 'Intermediate (Kotlin required)',
    hours: 30,
    accent: '#3DDC84',
    badge: 'AND',
    category: 'framework',
    stack: 'Kotlin',
    modules: [
        {
            title: 'Getting Started',
            description: 'Android Studio, the emulator, and your first running app.',
            lessons: [
                'Installing Android Studio',
                'Creating a project (Empty Compose Activity)',
                'Project anatomy: manifest, gradle, source sets',
                'Running on the emulator and a real device',
                'How an Android app starts (Activity basics)',
                'Logcat and debugging',
            ],
        },
        {
            title: 'Jetpack Compose Basics',
            description: 'Declarative UI: functions all the way down.',
            lessons: [
                '@Composable functions',
                'Text, Button, Image',
                'Modifiers: padding, size, background, clickable',
                'Row, Column, and Box layouts',
                'Arrangement and alignment',
                'Previews (@Preview)',
                'Exercise: profile card',
            ],
        },
        {
            title: 'State in Compose',
            description: 'The reactive model behind every Compose screen.',
            lessons: [
                'remember and mutableStateOf',
                'Recomposition: what re-runs and why',
                'State hoisting',
                'rememberSaveable and configuration changes',
                'derivedStateOf',
                'Exercise: interactive counter and form',
            ],
        },
        {
            title: 'Lists & Navigation',
            description: 'Scrollable content and multi-screen apps.',
            lessons: [
                'LazyColumn and LazyRow',
                'Keys and item content',
                'Navigation Compose setup',
                'Routes and arguments',
                'Back stack behavior',
                'Bottom navigation bar',
                'Exercise: list → detail flow',
            ],
        },
        {
            title: 'Theming & Material 3',
            description: 'Consistent, beautiful apps with Material Design.',
            lessons: [
                'MaterialTheme: colors, typography, shapes',
                'Dark theme support',
                'Dynamic color',
                'Reusable component styling',
                'Icons and resources',
            ],
        },
        {
            title: 'Architecture: ViewModel & UDF',
            description: 'Survive rotation and keep logic out of the UI.',
            lessons: [
                'Why ViewModel exists (lifecycles)',
                'ViewModel + StateFlow',
                'Unidirectional data flow (events up, state down)',
                'UI state classes',
                'collectAsStateWithLifecycle',
                'Repository pattern',
            ],
        },
        {
            title: 'Local Data',
            description: 'Store data on the device.',
            lessons: [
                'Room: entities, DAOs, database',
                'Flows from Room',
                'Migrations basics',
                'DataStore for preferences',
                'Exercise: offline notes',
            ],
        },
        {
            title: 'Networking',
            description: 'Talk to APIs with coroutines.',
            lessons: [
                'Retrofit setup with kotlinx.serialization',
                'Suspend API calls from ViewModels',
                'Loading/error/success UI states',
                'Coil for image loading',
                'Combining network + Room (offline-first idea)',
            ],
        },
        {
            title: 'Android Essentials',
            description: 'The platform pieces every app touches.',
            lessons: [
                'Activity and process lifecycle in practice',
                'Intents: opening screens and sharing',
                'Permissions (runtime requests)',
                'Notifications basics',
                'App icons and splash screens',
            ],
        },
        {
            title: 'Testing & Release',
            description: 'Quality checks, then Google Play.',
            lessons: [
                'Unit testing ViewModels',
                'Compose UI tests',
                'Building a release: signing configs',
                'App bundles and Play Console overview',
                'Crash reporting basics',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'A complete, installable Android app.',
            lessons: [
                'Scoping: expense tracker or habit app',
                'Screens and navigation map',
                'ViewModels and repositories',
                'Room persistence + API sync',
                'Theming and polish',
                'Tests and a signed release build',
            ],
        },
    ],
};
