import { CourseDefinition } from '../types';

export const angular: CourseDefinition = {
    id: 'angular',
    title: 'Angular Mastery',
    tagline: 'The full-featured enterprise framework — signals, DI, and RxJS included.',
    level: 'Intermediate (TypeScript required)',
    hours: 28,
    accent: '#DD0031',
    badge: 'NG',
    requires: ['node'],
    category: 'framework',
    stack: 'JavaScript',
    modules: [
        {
            title: 'Getting Started',
            description: 'The Angular platform and CLI-driven workflow.',
            lessons: [
                'What Angular is (vs AngularJS, vs React)',
                'Installing the Angular CLI',
                'ng new: workspace anatomy',
                'Serving, building, and generating with the CLI',
                'Standalone components (the modern default)',
                'Angular DevTools',
            ],
        },
        {
            title: 'Components & Templates',
            description: 'Angular’s building blocks and template syntax.',
            lessons: [
                'Component class + template + styles',
                'Interpolation and property binding',
                'Event binding',
                'Two-way binding',
                'Control flow: @if, @for, @switch',
                'Inputs and outputs between components',
                'Content projection (ng-content)',
                'Exercise: product list with child components',
            ],
        },
        {
            title: 'Signals & State',
            description: 'Angular’s modern reactivity model.',
            lessons: [
                'signal(): reactive values',
                'computed()',
                'effect()',
                'Signal inputs and model()',
                'Signals vs RxJS: when each fits',
                'Exercise: reactive shopping cart totals',
            ],
        },
        {
            title: 'Directives & Pipes',
            description: 'Extending HTML and formatting data.',
            lessons: [
                'Attribute directives (ngClass, ngStyle)',
                'Writing a custom directive',
                'Built-in pipes (date, currency, async)',
                'Writing a custom pipe',
                'Pure vs impure pipes',
            ],
        },
        {
            title: 'Services & Dependency Injection',
            description: 'The DI system that structures every Angular app.',
            lessons: [
                'Services and @Injectable',
                'inject() and constructor injection',
                'providedIn and provider scopes',
                'Hierarchical injectors',
                'Injection tokens and configuration',
                'Exercise: a logging + settings service',
            ],
        },
        {
            title: 'Forms',
            description: 'Both form systems, with validation done right.',
            lessons: [
                'Template-driven forms',
                'Reactive forms: FormControl, FormGroup',
                'Typed reactive forms',
                'Validators and custom validators',
                'Displaying validation errors',
                'Dynamic forms with FormArray',
            ],
        },
        {
            title: 'HTTP & Data',
            description: 'Talking to APIs with HttpClient.',
            lessons: [
                'provideHttpClient and making requests',
                'Typing responses',
                'Error handling',
                'Interceptors (auth tokens, logging)',
                'Loading states and the async pipe',
                'Exercise: CRUD against a REST API',
            ],
        },
        {
            title: 'Routing',
            description: 'Navigation, guards, and lazy loading.',
            lessons: [
                'Defining routes and router-outlet',
                'RouterLink and navigation',
                'Route parameters',
                'Child routes and layouts',
                'Route guards (auth)',
                'Lazy loading routes',
                'Resolvers',
            ],
        },
        {
            title: 'RxJS Essentials',
            description: 'Just enough observables to be dangerous (in a good way).',
            lessons: [
                'Observables vs promises',
                'Subscribing and unsubscribing',
                'Core operators: map, filter, tap',
                'switchMap and friends (avoiding nested subscribes)',
                'Subjects and BehaviorSubject',
                'Combining streams',
                'toSignal / toObservable interop',
            ],
        },
        {
            title: 'Testing',
            description: 'Unit and component tests the Angular way.',
            lessons: [
                'TestBed fundamentals',
                'Testing components and templates',
                'Testing services (and HTTP with HttpTestingController)',
                'Mocking dependencies',
                'What to cover in a real app',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'An enterprise-style app with auth, forms, and lazy routes.',
            lessons: [
                'Scoping: an admin dashboard',
                'Feature folders and routing skeleton',
                'Auth: interceptor + guards',
                'Reactive forms for data entry',
                'Signals-based state',
                'Tests for the critical paths',
                'Production build and deploy',
            ],
        },
    ],
};
