import { CourseDefinition } from '../types';

export const c: CourseDefinition = {
    id: 'c',
    title: 'C Programming',
    tagline: 'The language beneath everything — pointers, memory, and how computers really work.',
    level: 'Beginner → Advanced',
    hours: 30,
    accent: '#A8B9CC',
    badge: 'C',
    requires: ['cc'],
    modules: [
        {
            title: 'Getting Started',
            description: 'Why C still matters, and how source code becomes an executable.',
            lessons: [
                'Why learn C in the modern era',
                'Installing GCC or Clang',
                'Your first program: Hello World',
                'The compilation pipeline: preprocess, compile, assemble, link',
                'Structure of a C program (main, headers)',
                'Compiling with flags (-Wall, -g, -O2)',
            ],
        },
        {
            title: 'Variables & Types',
            description: 'C’s type system and formatted input/output.',
            lessons: [
                'Declaring variables',
                'Integer types: int, long, short, signed/unsigned',
                'char, float, and double',
                'sizeof and platform differences',
                'Constants: const and #define',
                'printf and format specifiers',
                'Reading input with scanf (and its dangers)',
                'Implicit and explicit type conversion',
            ],
        },
        {
            title: 'Operators & Expressions',
            description: 'From arithmetic to bit manipulation.',
            lessons: [
                'Arithmetic operators and integer division',
                'Relational and logical operators',
                'Increment and decrement (prefix vs postfix)',
                'Bitwise operators (&, |, ^, ~, <<, >>)',
                'Operator precedence and associativity',
                'Exercise: bit-flag toolkit',
            ],
        },
        {
            title: 'Control Flow',
            description: 'Decisions and loops in C.',
            lessons: [
                'if / else if / else',
                'switch statements and fall-through',
                'while and do...while loops',
                'for loops',
                'break and continue',
                'goto (and why to avoid it)',
                'Exercises: FizzBuzz, prime checker',
            ],
        },
        {
            title: 'Functions',
            description: 'Prototypes, recursion, and how C organizes programs.',
            lessons: [
                'Defining and calling functions',
                'Declarations vs definitions and prototypes',
                'Pass by value (there is no pass by reference)',
                'Recursion',
                'Storage classes: static and extern',
                'Header files and multi-file basics',
                'Exercise: recursive Fibonacci and iterative rewrite',
            ],
        },
        {
            title: 'Arrays & Strings',
            description: 'Contiguous data and C’s notorious string handling.',
            lessons: [
                'One-dimensional arrays',
                'Two-dimensional arrays',
                'Arrays and functions (decay)',
                'Strings as char arrays and the null terminator',
                'string.h: strlen, strcpy, strcmp, strcat',
                'Safe string handling (strncpy, snprintf)',
                'Buffer overflows and why they matter',
                'Exercise: word reverser',
            ],
        },
        {
            title: 'Pointers',
            description: 'The topic that defines C — mastered step by step.',
            lessons: [
                'What a pointer really is (addresses)',
                'The & and * operators',
                'Pointers and function arguments (simulating pass by reference)',
                'Pointers and arrays',
                'Pointer arithmetic',
                'Pointers to pointers',
                'const with pointers (all four combinations)',
                'Function pointers',
                'NULL and defensive pointer habits',
            ],
        },
        {
            title: 'Dynamic Memory',
            description: 'The heap: allocate it, use it, free it — correctly.',
            lessons: [
                'Stack vs heap',
                'malloc and free',
                'calloc and realloc',
                'Memory leaks and how to find them (valgrind)',
                'Use-after-free and double free bugs',
                'Building a dynamic array (growable buffer)',
                'Ownership conventions in C code',
            ],
        },
        {
            title: 'Structs, Unions & Enums',
            description: 'Custom data types and how they map to memory.',
            lessons: [
                'Defining and using structs',
                'typedef',
                'Nested structs',
                'Structs and pointers (the -> operator)',
                'Passing structs to functions',
                'Memory layout, padding, and alignment',
                'Unions',
                'Enums',
                'Bit fields',
            ],
        },
        {
            title: 'File I/O',
            description: 'Reading and writing files with the standard library.',
            lessons: [
                'fopen modes and fclose',
                'Reading lines with fgets',
                'fprintf and fscanf',
                'Character I/O: fgetc, fputc',
                'Binary files: fread and fwrite',
                'File positioning: fseek, ftell',
                'Error handling: errno and perror',
                'Exercise: CSV record reader',
            ],
        },
        {
            title: 'The Preprocessor & Multi-file Projects',
            description: 'Macros, include guards, and building bigger programs with make.',
            lessons: [
                '#include and header organization',
                '#define and function-like macros',
                'Macro pitfalls and parenthesization',
                'Conditional compilation (#ifdef)',
                'Include guards and #pragma once',
                'Splitting a program into modules',
                'Makefiles: targets, dependencies, variables',
            ],
        },
        {
            title: 'Data Structures in C',
            description: 'Build the classic data structures from scratch.',
            lessons: [
                'Singly linked lists',
                'Doubly linked lists',
                'Stacks',
                'Queues',
                'Hash tables (a simple implementation)',
                'Binary trees introduction',
                'Generic containers with void*',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'A real command-line tool in pure C.',
            lessons: [
                'Scoping the project (mini text database or shell)',
                'Parsing command-line arguments',
                'Designing the data structures',
                'Implementing core commands',
                'File persistence',
                'Testing and valgrind-clean memory',
                'Final review and extension ideas',
            ],
        },
    ],
};
