import { CourseDefinition } from '../types';

export const cpp: CourseDefinition = {
    id: 'cpp',
    title: 'C++ Mastery',
    tagline: 'High-performance programming: memory, OOP, templates, and modern C++.',
    level: 'Beginner → Advanced',
    hours: 45,
    accent: '#659AD2',
    badge: 'C++',
    modules: [
        {
            title: 'Getting Started',
            description: 'Set up a compiler and understand the build pipeline.',
            lessons: [
                'What is C++ and where it shines',
                'Installing a compiler (GCC/Clang/MSVC)',
                'Setting up your IDE',
                'Your first program: Hello World',
                'Compilation and linking explained',
                'Errors vs warnings',
                'The structure of a C++ program',
            ],
        },
        {
            title: 'The Basics',
            description: 'Variables, expressions, and talking to the user.',
            lessons: [
                'Variables and initialization',
                'Constants',
                'Naming conventions',
                'Mathematical expressions',
                'Order of operations',
                'Writing output with cout',
                'Reading input with cin',
                'Using the standard library',
                'Exercise: temperature converter',
            ],
        },
        {
            title: 'Data Types',
            description: 'Fundamental types, arrays, and conversions — with their pitfalls.',
            lessons: [
                'Fundamental types and sizeof',
                'Initialization styles (brace initialization)',
                'Integer overflow and narrowing',
                'Floating-point numbers',
                'Characters and C-style strings',
                'std::string first look',
                'Booleans',
                'Arrays',
                'Generating random numbers',
                'Implicit and explicit casting (static_cast)',
            ],
        },
        {
            title: 'Decision Making',
            description: 'Branching logic in C++.',
            lessons: [
                'Comparison operators',
                'Logical operators',
                'if statements and nesting',
                'The ternary operator',
                'switch statements',
                'Exercise: simple calculator',
            ],
        },
        {
            title: 'Loops',
            description: 'Repetition with for, while, and range-based loops.',
            lessons: [
                'for loops',
                'Range-based for loops',
                'while loops',
                'do...while loops',
                'break and continue',
                'Nested loops',
                'Exercises: number guessing game, patterns',
            ],
        },
        {
            title: 'Functions',
            description: 'Declarations, overloading, and organizing code across files.',
            lessons: [
                'Declaring and defining functions',
                'Arguments and default values',
                'Pass by value vs pass by reference',
                'Function overloading',
                'Scope and static local variables',
                'Inline functions',
                'Recursion',
                'Header files and prototypes',
                'Namespaces',
                'Organizing a multi-file project',
            ],
        },
        {
            title: 'Pointers & Memory',
            description: 'The heart of C++: stack, heap, pointers, and smart pointers.',
            lessons: [
                'The memory model: stack vs heap',
                'Pointers and the address-of operator',
                'Dereferencing pointers',
                'Pointers and arrays',
                'Pointer arithmetic',
                'Dynamic allocation with new and delete',
                'Dangling pointers and memory leaks',
                'References vs pointers',
                'Smart pointers: unique_ptr',
                'Smart pointers: shared_ptr and weak_ptr',
                'RAII: the idiom that defines C++',
            ],
        },
        {
            title: 'Structures & Enumerations',
            description: 'Grouping related data into custom types.',
            lessons: [
                'Defining structures',
                'Member initialization',
                'Structs and functions',
                'Unions',
                'Enumerations and enum class',
                'Exercise: modeling a 2D point library',
            ],
        },
        {
            title: 'Strings & Streams',
            description: 'Text processing and file input/output.',
            lessons: [
                'std::string in depth',
                'string_view',
                'Converting between strings and numbers',
                'Stream basics: cin/cout formatting',
                'Reading and writing text files',
                'Binary file I/O',
                'stringstream',
            ],
        },
        {
            title: 'Classes & Object-Oriented Programming',
            description: 'Constructors, destructors, copy/move semantics, and operator overloading.',
            lessons: [
                'Defining classes',
                'Access modifiers and encapsulation',
                'Constructors and member initializer lists',
                'Destructors',
                'The copy constructor',
                'Move semantics and rvalue references',
                'The rule of five (and rule of zero)',
                'Operator overloading',
                'const correctness',
                'Static members',
                'Friend functions and classes',
            ],
        },
        {
            title: 'Inheritance & Polymorphism',
            description: 'Virtual functions and how runtime polymorphism actually works.',
            lessons: [
                'Base and derived classes',
                'Protected members',
                'Constructors in inheritance',
                'Virtual functions and vtables',
                'Overriding (override and final)',
                'Abstract classes and pure virtual functions',
                'Object slicing',
                'Virtual destructors',
                'Multiple inheritance and its hazards',
            ],
        },
        {
            title: 'Templates & the STL',
            description: 'Generic programming plus the containers and algorithms you get for free.',
            lessons: [
                'Function templates',
                'Class templates',
                'Template specialization basics',
                'STL containers: vector, array, list',
                'STL containers: map, set, unordered_map',
                'Iterators',
                'Algorithms: sort, find, transform, accumulate',
                'Lambda expressions',
                'Choosing the right container',
            ],
        },
        {
            title: 'Exceptions & Error Handling',
            description: 'Fail safely with exceptions and RAII.',
            lessons: [
                'Throwing and catching exceptions',
                'Standard exception classes',
                'Catch by reference',
                'noexcept',
                'Exception safety guarantees',
                'Error codes vs exceptions vs std::optional',
            ],
        },
        {
            title: 'Modern C++ & Capstone',
            description: 'C++17/20 highlights, tooling, and a full project.',
            lessons: [
                'auto and type deduction',
                'Structured bindings',
                'std::optional, std::variant',
                'Ranges (C++20 overview)',
                'Building with CMake',
                'Debugging and sanitizers (ASan, valgrind)',
                'Capstone: design the project (bank system / game of life)',
                'Capstone: implement, test, and review',
            ],
        },
    ],
};
