import { CourseDefinition } from '../types';

export const csharp: CourseDefinition = {
    id: 'csharp',
    title: 'C# & .NET Mastery',
    tagline: 'From console apps to LINQ and async — the full C# developer path.',
    level: 'Beginner → Advanced',
    hours: 35,
    accent: '#68217A',
    badge: 'C#',
    requires: ['dotnet'],
    modules: [
        {
            title: 'Getting Started',
            description: 'C#, .NET, and your first console application.',
            lessons: [
                'What is C# and what is .NET',
                'Installing the .NET SDK',
                'Visual Studio vs VS Code + CLI',
                'Your first console app (dotnet new, dotnet run)',
                'How C# compiles: IL and the CLR',
                'Top-level statements vs Main',
            ],
        },
        {
            title: 'Primitive Types & Expressions',
            description: 'Variables, operators, and type conversion.',
            lessons: [
                'Variables and constants',
                'Primitive types and memory',
                'Overflow and checked contexts',
                'Scope',
                'Type conversion (implicit, explicit, Convert)',
                'Operators',
                'Comments and readable code',
                'Exercise: swapping variables and simple math',
            ],
        },
        {
            title: 'Non-Primitive Types',
            description: 'Classes, arrays, strings, and the value/reference divide.',
            lessons: [
                'Classes: a first look',
                'Namespaces and using',
                'Structs',
                'Arrays',
                'Strings and immutability',
                'Verbatim and interpolated strings',
                'Enums',
                'Reference types vs value types',
            ],
        },
        {
            title: 'Control Flow',
            description: 'Conditionals, loops, and iteration patterns.',
            lessons: [
                'if / else and switch',
                'Switch expressions (modern C#)',
                'for and foreach',
                'while and do...while',
                'break and continue',
                'The Random class',
                'Exercises: fizzbuzz, max, counting vowels',
            ],
        },
        {
            title: 'Arrays & Lists',
            description: 'Working fluently with collections of data.',
            lessons: [
                'Multi-dimensional and jagged arrays',
                'Array methods (Sort, IndexOf, Copy)',
                'List<T> and common operations',
                'Choosing arrays vs lists',
                'Exercise: building a number stats tool',
            ],
        },
        {
            title: 'Text, Dates & Files',
            description: 'The everyday APIs: strings, DateTime, and the file system.',
            lessons: [
                'String methods in depth',
                'StringBuilder',
                'DateTime and TimeSpan',
                'Formatting and parsing dates',
                'File, FileInfo, Directory, Path',
                'Reading and writing text files',
                'Defensive file handling',
                'Exercise: log-file summarizer',
            ],
        },
        {
            title: 'Classes in Depth',
            description: 'Constructors, properties, indexers — intermediate OOP.',
            lessons: [
                'Fields and initialization',
                'Constructors and constructor overloading',
                'Object initializers',
                'Methods: overloading, params, ref and out',
                'Properties and auto-properties',
                'Indexers',
                'Static members',
                'this and member access',
            ],
        },
        {
            title: 'Association, Inheritance & Polymorphism',
            description: 'Relationships between classes — and the traps of inheritance.',
            lessons: [
                'Class coupling',
                'Composition vs inheritance',
                'Inheritance and access modifiers',
                'Constructors and inheritance',
                'Upcasting and downcasting',
                'Boxing and unboxing',
                'Method overriding (virtual / override)',
                'Abstract classes and members',
                'Sealed classes',
                'Polymorphism in practice',
            ],
        },
        {
            title: 'Interfaces',
            description: 'Loose coupling, extensibility, and testability.',
            lessons: [
                'What interfaces are (and are not)',
                'Interfaces and testability',
                'Interfaces and extensibility',
                'Explicit interface implementation',
                'Interfaces vs abstract classes',
                'Default interface members overview',
                'Exercise: notification channels behind an interface',
            ],
        },
        {
            title: 'Advanced C#',
            description: 'Generics, delegates, LINQ, events, and async — the power features.',
            lessons: [
                'Generics and constraints',
                'Delegates',
                'Lambda expressions',
                'Events and event handlers',
                'Extension methods',
                'LINQ: query and method syntax',
                'LINQ: filtering, projecting, ordering, grouping',
                'Deferred execution',
                'Nullable value types',
                'dynamic',
                'Exception handling in depth (custom exceptions, filters)',
                'async / await and Task',
            ],
        },
        {
            title: 'Modern C# & the .NET Ecosystem',
            description: 'The features and tools of current .NET.',
            lessons: [
                'Records and with-expressions',
                'Pattern matching deep dive',
                'Nullable reference types',
                'NuGet packages',
                'Unit testing with xUnit',
                'Dependency injection in .NET',
                'A tour of ASP.NET Core minimal APIs',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'A complete task-management API with tests.',
            lessons: [
                'Scoping and designing the domain',
                'Minimal API endpoints',
                'Services behind interfaces + DI',
                'Persistence with EF Core (intro)',
                'Validation and error handling',
                'Unit and integration tests',
                'Final review and next steps (ASP.NET, MAUI, Unity)',
            ],
        },
    ],
};
