import { CourseDefinition } from '../types';
import { SECURITY_ETHICS_GUIDELINES } from './guidelines';

export const cybersecurity: CourseDefinition = {
    id: 'cybersecurity',
    title: 'Cybersecurity Fundamentals',
    tagline: 'Understand how attacks work and how to defend against them, practiced legally in your own lab.',
    level: 'Beginner → Intermediate',
    hours: 45,
    accent: '#EF4444',
    badge: 'SEC',
    category: 'security',
    stack: 'Linux',
    tutorGuidelines: [
        ...SECURITY_ETHICS_GUIDELINES,
        'Many lessons need Linux tools. Check the learner\'s OS first (uname -a, or ask). If they are on Windows, suggest WSL or a Linux VM and adapt the commands.',
        'Use the Python standard library (hashlib, secrets, ssl, socket) where possible. Check third-party packages such as cryptography are installed before importing them.',
    ],
    modules: [
        {
            title: 'Security Foundations',
            description: 'The core ideas every security professional builds on.',
            lessons: [
                'The CIA triad: confidentiality, integrity, availability',
                'Threats, vulnerabilities, and risk',
                'Who attacks, and why',
                'Defense in depth',
                'Ethics and the law: why authorization matters',
                'Security career paths',
                'Setting up a safe home lab with VMs and Docker',
            ],
        },
        {
            title: 'Linux for Security',
            description: 'The operating system most security work happens on.',
            lessons: [
                'The Linux file system',
                'Users, groups, and sudo',
                'File permissions and ownership',
                'Processes and services',
                'Reading system logs',
                'Bash essentials for security work',
            ],
        },
        {
            title: 'Networking for Security',
            description: 'You cannot defend a network you do not understand.',
            lessons: [
                'The OSI and TCP/IP models',
                'IP addresses, subnets, and ports',
                'The TCP handshake',
                'DNS and how it can be abused',
                'HTTP and HTTPS',
                'Capturing your own traffic with tcpdump or Wireshark',
                'Firewalls: what they can and cannot do',
            ],
        },
        {
            title: 'Cryptography',
            description: 'Protecting data at rest and in transit.',
            lessons: [
                'Encoding vs encryption vs hashing',
                'Symmetric encryption (AES)',
                'Asymmetric encryption (RSA and elliptic curves)',
                'Hash functions and integrity checks',
                'Password hashing and salting (bcrypt, Argon2)',
                'Digital signatures and certificates',
                'How TLS secures HTTPS',
                'Exercise: hashing and encryption in Python',
            ],
        },
        {
            title: 'Authentication & Access Control',
            description: 'Proving who you are and limiting what you can do.',
            lessons: [
                'Passwords and password managers',
                'Multi-factor authentication',
                'Sessions, cookies, and tokens',
                'OAuth 2.0 and single sign-on: the basics',
                'The principle of least privilege',
                'Exercise: a secure login flow',
            ],
        },
        {
            title: 'Web Application Security',
            description: 'The most common way real systems get breached.',
            lessons: [
                'The OWASP Top 10 overview',
                'SQL injection and parameterized queries',
                'Cross-site scripting (XSS) and output encoding',
                'Cross-site request forgery (CSRF)',
                'Broken access control and IDOR',
                'Security headers and CORS',
                'Lab: exploring OWASP Juice Shop locally',
            ],
        },
        {
            title: 'Defending Systems & Networks',
            description: 'Harden machines and watch for trouble.',
            lessons: [
                'Hardening a Linux server',
                'Configuring a host firewall',
                'Securing SSH',
                'Patch and update management',
                'Scanning your own lab with nmap',
                'Intrusion detection concepts',
            ],
        },
        {
            title: 'Threats & Malware',
            description: 'Recognize what you are up against.',
            lessons: [
                'Types of malware: viruses, worms, trojans, ransomware',
                'Phishing and social engineering',
                'Spotting a phishing email',
                'Denial-of-service attacks: the concepts',
                'Supply chain attacks',
            ],
        },
        {
            title: 'Security Operations & Incident Response',
            description: 'Detect, respond, and recover when something goes wrong.',
            lessons: [
                'Logging and monitoring',
                'SIEM concepts',
                'Reading logs to spot suspicious activity',
                'The incident response lifecycle',
                'Digital forensics basics',
                'Backups and recovery',
            ],
        },
        {
            title: 'Ethical Hacking Methodology',
            description: 'How professional penetration testers work, legally and in scope.',
            lessons: [
                'Rules of engagement and scope',
                'The phases of a penetration test',
                'Reconnaissance on your own assets',
                'Vulnerability scanning',
                'Exploitation in a lab environment',
                'Writing a penetration test report',
                'CTFs and bug bounty programs',
            ],
        },
        {
            title: 'Governance, Risk & Compliance',
            description: 'Security as an organization, not just a technology.',
            lessons: [
                'Risk assessment',
                'Security policies',
                'Frameworks: NIST CSF and ISO 27001 at a glance',
                'Privacy regulations at a glance',
                'Security awareness training',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'Build, attack, and defend your own application in a lab.',
            lessons: [
                'Setting up a small web app in your lab',
                'Threat modeling it with STRIDE',
                'Testing it for common vulnerabilities',
                'Fixing what you found',
                'Hardening the server it runs on',
                'Writing a security report',
            ],
        },
    ],
};
