import { CourseDefinition } from '../types';

export const django: CourseDefinition = {
    id: 'django',
    title: 'Django Mastery',
    tagline: 'Python’s batteries-included web framework — from models to deployment.',
    level: 'Intermediate (Python required)',
    hours: 26,
    accent: '#44B78B',
    badge: 'DJ',
    category: 'framework',
    stack: 'Python',
    modules: [
        {
            title: 'Getting Started',
            description: 'Django’s philosophy and your first running project.',
            lessons: [
                'What Django gives you out of the box',
                'Setting up a virtual environment and installing Django',
                'django-admin startproject: anatomy of a project',
                'The development server',
                'Projects vs apps (startapp)',
                'How a request flows through Django',
            ],
        },
        {
            title: 'Views & URLs',
            description: 'Mapping URLs to Python functions.',
            lessons: [
                'URL patterns and urls.py',
                'Function-based views',
                'Path converters (int, slug)',
                'Including app URL configs',
                'HttpRequest and HttpResponse',
                'Redirects and 404s',
            ],
        },
        {
            title: 'Templates',
            description: 'Django’s template language for server-rendered pages.',
            lessons: [
                'Template configuration and rendering',
                'Variables, filters, and tags',
                'Template inheritance (base.html)',
                'Including partials',
                'Static files (CSS/JS/images)',
                'URL reversing in templates',
                'Exercise: multi-page site with a shared layout',
            ],
        },
        {
            title: 'Models & the ORM',
            description: 'The heart of Django: define data in Python, let Django do SQL.',
            lessons: [
                'Defining models and field types',
                'Migrations: makemigrations and migrate',
                'Creating and querying objects (QuerySets)',
                'Filtering, excluding, ordering',
                'Relationships: ForeignKey, ManyToMany, OneToOne',
                'Following relationships in queries',
                'Aggregation and annotation',
                'Model methods and __str__',
                'The N+1 problem: select_related / prefetch_related',
            ],
        },
        {
            title: 'The Admin Site',
            description: 'The killer feature: a production CRUD UI for free.',
            lessons: [
                'Creating a superuser',
                'Registering models',
                'Customizing list displays and filters',
                'Search and inline editing',
                'Admin actions',
            ],
        },
        {
            title: 'Forms',
            description: 'Validated user input without the boilerplate.',
            lessons: [
                'Form classes and fields',
                'Rendering forms in templates',
                'Validation and cleaned_data',
                'ModelForm',
                'CSRF protection explained',
                'Custom validation methods',
                'Exercise: contact + review forms',
            ],
        },
        {
            title: 'Class-Based Views & CRUD',
            description: 'Generic views that write the common patterns for you.',
            lessons: [
                'From function to class-based views',
                'ListView and DetailView',
                'CreateView, UpdateView, DeleteView',
                'Success URLs and messages framework',
                'When to stay with function-based views',
            ],
        },
        {
            title: 'Users & Authentication',
            description: 'Django’s built-in auth, used properly.',
            lessons: [
                'The User model and auth app',
                'Login and logout views',
                'Registration flow',
                'login_required and mixins',
                'Permissions and groups',
                'Customizing the user model (and why to do it early)',
            ],
        },
        {
            title: 'Django REST Framework',
            description: 'Turn your project into a JSON API.',
            lessons: [
                'Why DRF and installation',
                'Serializers and ModelSerializer',
                'APIView and generic views',
                'ViewSets and routers',
                'Authentication and permissions in DRF',
                'Pagination and filtering',
                'Exercise: API for your models',
            ],
        },
        {
            title: 'Testing & Deployment',
            description: 'Ship a Django site the professional way.',
            lessons: [
                'Writing tests with the Django test client',
                'Factories and fixtures',
                'Settings for dev vs production',
                'PostgreSQL in production',
                'Static files with WhiteNoise',
                'Gunicorn + reverse proxy',
                'Environment variables and secrets',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'A complete database-driven site with auth and an API.',
            lessons: [
                'Scoping: course platform or marketplace',
                'Models and admin setup',
                'Views, templates, and forms',
                'Auth and permissions',
                'REST API endpoints',
                'Tests for critical flows',
                'Deploy to production',
            ],
        },
    ],
};
