import { CourseDefinition } from '../types';

export const go: CourseDefinition = {
    id: 'go',
    title: 'Go Mastery',
    tagline: 'Simple, fast, concurrent — the language of cloud infrastructure.',
    level: 'Beginner → Advanced',
    hours: 25,
    accent: '#00ADD8',
    badge: 'GO',
    requires: ['go'],
    modules: [
        {
            title: 'Getting Started',
            description: 'Install Go, learn the toolchain, and ship your first binary.',
            lessons: [
                'Why Go: simplicity and speed',
                'Installing Go and setting up your editor',
                'Your first program and go run',
                'go build: compiling to a single binary',
                'Modules: go mod init',
                'gofmt and the Go way of formatting',
                'Packages and the main function',
            ],
        },
        {
            title: 'Variables & Types',
            description: 'Declarations, zero values, and Go’s no-surprises type system.',
            lessons: [
                'var declarations and short declaration (:=)',
                'Basic types: int, float64, string, bool',
                'Zero values',
                'Constants and iota',
                'Explicit type conversion (no implicit casts)',
                'fmt: Println, Printf, and verbs',
                'Getting user input',
            ],
        },
        {
            title: 'Control Flow',
            description: 'One loop to rule them all, plus Go’s flexible switch.',
            lessons: [
                'if with initialization statements',
                'switch (expression and no-condition forms)',
                'The for loop: three forms',
                'range over slices, maps, and strings',
                'break, continue, and labels',
                'defer: a first look',
                'Exercise: FizzBuzz and a CLI menu',
            ],
        },
        {
            title: 'Functions',
            description: 'Multiple returns, closures, and Go’s error-first style.',
            lessons: [
                'Defining functions',
                'Multiple return values',
                'Named return values',
                'Variadic functions',
                'Functions as values',
                'Closures',
                'defer, panic, and recover',
            ],
        },
        {
            title: 'Slices, Maps & Strings',
            description: 'Go’s core data structures and how they behave in memory.',
            lessons: [
                'Arrays vs slices',
                'Slice internals: length, capacity, backing array',
                'append and copy',
                'Slicing slices (and the gotchas)',
                'Maps: create, read, write, delete',
                'The comma-ok idiom',
                'Strings, bytes, and runes (UTF-8)',
                'strings and strconv packages',
            ],
        },
        {
            title: 'Structs & Methods',
            description: 'Go’s take on objects: plain data plus methods.',
            lessons: [
                'Defining structs',
                'Struct literals and field access',
                'Methods and receivers',
                'Pointer vs value receivers',
                'Constructor functions (the New pattern)',
                'Struct embedding (composition)',
                'Struct tags',
            ],
        },
        {
            title: 'Interfaces',
            description: 'Implicit interfaces: Go’s quiet superpower.',
            lessons: [
                'Interfaces are satisfied implicitly',
                'Interface values and dynamic types',
                'The empty interface and any',
                'Type assertions',
                'Type switches',
                'Standard interfaces: Stringer, error, io.Reader/Writer',
                'Designing small interfaces',
                'Exercise: pluggable storage backends',
            ],
        },
        {
            title: 'Error Handling',
            description: 'Errors are values — handle them explicitly and well.',
            lessons: [
                'The error interface',
                'errors.New and fmt.Errorf',
                'Wrapping errors with %w',
                'errors.Is and errors.As',
                'Sentinel errors vs custom error types',
                'When to panic (almost never)',
                'Error-handling patterns in real code',
            ],
        },
        {
            title: 'Concurrency',
            description: 'Goroutines and channels — the reason many teams choose Go.',
            lessons: [
                'Goroutines',
                'Channels: send, receive, close',
                'Buffered vs unbuffered channels',
                'select',
                'sync.WaitGroup',
                'Mutexes and the race detector',
                'Worker pools',
                'Pipelines and fan-in/fan-out',
                'context: cancellation and deadlines',
                'Common concurrency pitfalls',
            ],
        },
        {
            title: 'Packages, Testing & Generics',
            description: 'Structuring, testing, and generalizing real Go projects.',
            lessons: [
                'Designing packages and exported names',
                'Project layout conventions',
                'go test and table-driven tests',
                'Benchmarks and examples',
                'go vet and staticcheck',
                'Generics: type parameters and constraints',
            ],
        },
        {
            title: 'The Standard Library in Practice',
            description: 'Build real things with what ships in the box.',
            lessons: [
                'net/http: writing an HTTP server',
                'net/http: clients and timeouts',
                'encoding/json: marshal and unmarshal',
                'os, io, and bufio',
                'time',
                'flag: command-line parsing',
                'database/sql introduction',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'A production-style REST API or CLI tool, start to finish.',
            lessons: [
                'Scoping the project (REST API for tasks)',
                'Designing handlers and routes',
                'JSON request/response handling',
                'Storage layer behind an interface',
                'Concurrency where it helps',
                'Tests for handlers and storage',
                'Dockerfile and shipping the binary',
            ],
        },
    ],
};
