import { Course } from '../types';

export const htmlCss: Course = {
    id: 'html-css',
    title: 'HTML & CSS: Web Foundations',
    tagline: 'Build beautiful, responsive websites from a blank file to a deployed portfolio.',
    level: 'Beginner → Advanced',
    hours: 25,
    accent: '#E44D26',
    badge: '<>',
    modules: [
        {
            title: 'Getting Started',
            description: 'How the web works and your first real page.',
            lessons: [
                'How the web works: browsers, servers, HTTP',
                'HTML, CSS, and JavaScript: who does what',
                'Setting up your editor (Emmet, live preview)',
                'Your first web page',
                'Inspecting pages with DevTools',
                'Validating your HTML',
            ],
        },
        {
            title: 'HTML Foundations',
            description: 'The document structure and essential elements.',
            lessons: [
                'Document structure: doctype, head, body',
                'Headings and paragraphs',
                'Text formatting and entities',
                'Lists: ul, ol, dl',
                'Hyperlinks (absolute, relative, fragments)',
                'Images and the alt attribute',
                'div and span: generic containers',
                'Comments and readable markup',
            ],
        },
        {
            title: 'More HTML: Structure & Forms',
            description: 'Semantic layout, tables, media, and interactive forms.',
            lessons: [
                'Semantic elements: header, nav, main, article, aside, footer',
                'Why semantics matter (accessibility & SEO)',
                'Tables done right',
                'Forms: input types, labels, placeholders',
                'Select, textarea, checkboxes, radios',
                'Built-in form validation attributes',
                'Audio and video',
                'iframes',
                'Project: structure a full article page',
            ],
        },
        {
            title: 'CSS Basics',
            description: 'Selectors, the cascade, and styling fundamentals.',
            lessons: [
                'Ways to provide CSS (external wins)',
                'Normalizing browser styles',
                'Basic selectors (element, class, id, attribute)',
                'Relational selectors (descendant, child, sibling)',
                'Pseudo-classes (:hover, :first-child, :nth-child)',
                'Pseudo-elements (::before, ::after)',
                'Specificity and the cascade',
                'Inheritance',
                'Colors: hex, rgb, hsl',
                'Gradients, borders, and shadows',
            ],
        },
        {
            title: 'The Box Model & Layout',
            description: 'How every element takes up space on the page.',
            lessons: [
                'The box model: content, padding, border, margin',
                'Margin collapsing',
                'Sizing and box-sizing: border-box',
                'Overflow',
                'Measurement units: px, %, em, rem, vw/vh',
                'display: block, inline, inline-block',
                'Positioning: static, relative, absolute, fixed, sticky',
                'z-index and stacking contexts',
                'Floats (legacy, but you will meet them)',
            ],
        },
        {
            title: 'Flexbox',
            description: 'One-dimensional layout for navbars, cards, and centering anything.',
            lessons: [
                'Flex containers and flex items',
                'Main axis vs cross axis',
                'justify-content and align-items',
                'flex-wrap and align-content',
                'flex-grow, flex-shrink, flex-basis',
                'The flex shorthand',
                'Perfect centering',
                'Project: responsive navbar and card row',
            ],
        },
        {
            title: 'CSS Grid',
            description: 'Two-dimensional layout for full page structures.',
            lessons: [
                'Defining a grid: rows and columns',
                'The fr unit, repeat(), minmax()',
                'Placing items (line numbers and spans)',
                'Named grid areas',
                'Gaps',
                'auto-fit and auto-fill',
                'Grid vs Flexbox: choosing the right tool',
                'Project: magazine-style layout',
            ],
        },
        {
            title: 'Responsive Design',
            description: 'One site, every screen size.',
            lessons: [
                'Mobile-first thinking',
                'The viewport meta tag',
                'Media queries',
                'Choosing breakpoints',
                'Responsive typography and fluid units',
                'Responsive images: srcset and picture',
                'Testing across devices in DevTools',
                'Project: making the layout fully responsive',
            ],
        },
        {
            title: 'Typography & Color',
            description: 'The design skills that separate amateur sites from professional ones.',
            lessons: [
                'Web-safe fonts and font stacks',
                'Google Fonts and @font-face',
                'Font size scales and hierarchy',
                'Line height, letter spacing, and measure',
                'Vertical rhythm',
                'Building a color palette',
                'Contrast and accessibility (WCAG basics)',
            ],
        },
        {
            title: 'Transitions, Transforms & Animations',
            description: 'Bring interfaces to life — tastefully.',
            lessons: [
                '2D transforms: translate, rotate, scale, skew',
                '3D transforms and perspective',
                'Transitions and timing functions',
                'Keyframe animations',
                'Animating performantly (transform & opacity)',
                'prefers-reduced-motion',
                'Project: animated hero section',
            ],
        },
        {
            title: 'Writing Maintainable CSS',
            description: 'CSS that scales beyond a single page.',
            lessons: [
                'Naming with BEM',
                'CSS custom properties (variables)',
                'Organizing stylesheets',
                'Utility classes and when they help',
                'Sass overview (nesting, partials)',
                'Tailwind CSS overview',
            ],
        },
        {
            title: 'Capstone: Portfolio Website',
            description: 'Design, build, and deploy your personal portfolio.',
            lessons: [
                'Planning sections and content',
                'Designing the look (spacing, type, color)',
                'Building the HTML structure',
                'Styling with Grid and Flexbox',
                'Responsive pass across breakpoints',
                'Accessibility audit',
                'Performance: optimizing images and CSS',
                'Deploying to GitHub Pages or Netlify',
            ],
        },
    ],
};
