import { CourseDefinition } from '../types';
import * as ex from './exercises/javascript';

export const javascript: CourseDefinition = {
    id: 'javascript',
    title: 'JavaScript: The Complete Path',
    tagline: 'The language of the web — from basics to async mastery.',
    level: 'Beginner → Advanced',
    hours: 35,
    accent: '#F7DF1E',
    badge: 'JS',
    requires: ['node'],
    modules: [
        {
            title: 'Getting Started',
            description: 'What JavaScript is, where it runs, and how to set up a professional workflow.',
            lessons: [
                'What is JavaScript and what can it do',
                'JavaScript in the browser vs Node.js',
                'Setting up your editor and dev environment',
                { title: 'Your first script and the browser console', exercise: ex.helloWorld },
                'Linking scripts to HTML and separation of concerns',
                'Statements, expressions, and comments',
            ],
        },
        {
            title: 'Basics: Variables & Types',
            description: 'The core value types and how JavaScript treats them.',
            lessons: [
                'Variables with let and const (and why not var)',
                'Primitive types: string, number, boolean, undefined, null',
                'Dynamic typing and typeof',
                'Objects: your first look',
                'Arrays: your first look',
                'Functions: your first look',
                { title: 'Template literals', exercise: ex.templateLiterals },
            ],
        },
        {
            title: 'Operators',
            description: 'Every operator you will actually use, and the traps to avoid.',
            lessons: [
                'Arithmetic and assignment operators',
                'Comparison operators',
                'Strict equality (===) vs loose equality (==)',
                { title: 'Ternary operator', exercise: ex.ternary },
                'Logical operators and non-boolean operands',
                { title: 'Nullish coalescing (??)', exercise: ex.nullish },
                'Operator precedence',
            ],
        },
        {
            title: 'Control Flow',
            description: 'Branching and looping through data.',
            lessons: [
                'if...else and else if',
                { title: 'switch...case', exercise: ex.switchCase },
                { title: 'for loops', exercise: ex.forLoop },
                'while and do...while',
                'break and continue',
                'for...in vs for...of',
                { title: 'Exercises: FizzBuzz, max of numbers, star pattern', exercise: ex.largest },
            ],
        },
        {
            title: 'Objects',
            description: 'The heart of JavaScript: creating, cloning, and working with objects.',
            lessons: [
                { title: 'Object literals', exercise: ex.objectLiterals },
                'Factory functions',
                'Constructor functions',
                'Dynamic nature of objects',
                'The this keyword (first look)',
                'Cloning objects (spread, Object.assign)',
                'Garbage collection',
                'Built-ins: Math, String, Date',
                'Exercise: address and blog post objects',
            ],
        },
        {
            title: 'Arrays',
            description: 'Every array method that matters, with real use cases.',
            lessons: [
                'Adding and finding elements',
                'Removing elements and emptying arrays',
                'Combining and slicing arrays',
                'The spread operator',
                'Iterating arrays',
                'Joining arrays and strings',
                'Sorting and comparing',
                'Testing elements (every, some)',
                'Filtering, mapping, and chaining',
                'Reducing an array',
                'Exercise: array utilities from scratch',
            ],
        },
        {
            title: 'Functions in Depth',
            description: 'Closures, this, arrow functions — the topics interviews love.',
            lessons: [
                'Function declarations vs expressions',
                'Hoisting',
                'The arguments object and rest parameters',
                'Default parameters',
                'Getters and setters',
                'Local vs global scope, let vs var',
                'Closures explained',
                'The this keyword in depth',
                'Changing this: call, apply, bind',
                'Arrow functions and lexical this',
            ],
        },
        {
            title: 'Object-Oriented JavaScript & Prototypes',
            description: 'How inheritance really works under the hood, then the ES6 class syntax.',
            lessons: [
                'The four pillars of OOP',
                'Prototypes and prototypical inheritance',
                'Prototype vs instance members',
                'Property descriptors',
                'ES6 classes',
                'Static methods',
                'Private members (# fields, symbols, WeakMaps)',
                'Getters and setters in classes',
                'Inheritance and method overriding',
                'Polymorphism',
                'Composition over inheritance (mixins)',
                'Exercise: building a Stack class',
            ],
        },
        {
            title: 'Modern JavaScript (ES6+)',
            description: 'The modern syntax and features every codebase uses today.',
            lessons: [
                'Modules: import and export',
                'CommonJS vs ES Modules',
                'Destructuring objects and arrays',
                'Optional chaining (?.)',
                'Symbols',
                'Iterators and generators',
                'Map and Set',
                'Tagged templates',
                'Transpiling and bundling overview (Babel, Vite)',
            ],
        },
        {
            title: 'Asynchronous JavaScript',
            description: 'The event loop, promises, and async/await — demystified.',
            lessons: [
                'Synchronous vs asynchronous code',
                'The event loop and callback queue',
                'Callbacks and callback hell',
                'Promises: consuming and creating',
                'Chaining promises',
                'Promise.all, allSettled, race',
                'async / await',
                'Error handling in async code',
                'Exercise: converting callback code to async/await',
            ],
        },
        {
            title: 'The DOM & Events',
            description: 'Make web pages interactive: select, modify, and react to the page.',
            lessons: [
                'The DOM tree',
                'Selecting elements (querySelector and friends)',
                'Changing content, attributes, and styles',
                'Creating and removing elements',
                'Events and addEventListener',
                'The event object',
                'Event bubbling and delegation',
                'Working with forms',
                'Fetching data with fetch()',
                'Project: dynamic search-and-filter list',
            ],
        },
        {
            title: 'Error Handling & Debugging',
            description: 'Find and fix bugs like a professional.',
            lessons: [
                'Error types and reading stack traces',
                'try / catch / finally and throwing errors',
                'Custom error classes',
                'Debugging with breakpoints in DevTools',
                'console beyond console.log',
                'Defensive programming patterns',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'Build a complete interactive browser app from scratch.',
            lessons: [
                'Scoping the project (quiz game or expense tracker)',
                'Structuring modules and state',
                'Building the UI and rendering logic',
                'Handling user events and validation',
                'Persisting with localStorage',
                'Fetching from a public API',
                'Polish, refactor, and deploy',
            ],
        },
    ],
};
