import { CourseDefinition } from '../types';

export const java: CourseDefinition = {
    id: 'java',
    title: 'Java: The Complete Path',
    tagline: 'From the JVM to streams and multithreading — job-ready Java.',
    level: 'Beginner → Advanced',
    hours: 40,
    accent: '#E76F00',
    badge: 'JAVA',
    modules: [
        {
            title: 'Getting Started',
            description: 'The Java platform explained, plus your first running program.',
            lessons: [
                'What is Java: JDK, JRE, and the JVM',
                'Installing the JDK',
                'Setting up IntelliJ IDEA (or VS Code)',
                'Anatomy of a Java program: classes and main',
                'Your first program: Hello World',
                'How Java code is compiled and executed (bytecode)',
                'Java editions and where Java is used',
            ],
        },
        {
            title: 'Types & Variables',
            description: 'Primitives, references, strings, and arrays — the raw material of every program.',
            lessons: [
                'Variables and constants',
                'Primitive types and memory',
                'Reference types vs primitives',
                'Strings and common String methods',
                'Escape sequences',
                'Arrays (one-dimensional)',
                'Multi-dimensional arrays',
                'Arithmetic operators and casting',
                'The Math class',
                'Formatting numbers (NumberFormat)',
                'Reading input with Scanner',
                'Project: mortgage calculator (part 1)',
            ],
        },
        {
            title: 'Control Flow',
            description: 'Decisions and loops with clean, idiomatic Java.',
            lessons: [
                'Comparison and logical operators',
                'if statements and simplifying them',
                'The ternary operator',
                'switch statements (and switch expressions)',
                'for loops',
                'while and do...while loops',
                'break and continue',
                'for-each loops',
                'Exercise: FizzBuzz',
                'Project: mortgage calculator (part 2, validation)',
            ],
        },
        {
            title: 'Clean Coding with Methods',
            description: 'Break programs into well-named, single-purpose methods.',
            lessons: [
                'Creating methods',
                'Parameters and return values',
                'Method overloading',
                'Refactoring repetitive code into methods',
                'Organizing a program top-down',
                'Project: refactoring the mortgage calculator',
            ],
        },
        {
            title: 'Classes & Objects',
            description: 'Object-oriented programming, starting from encapsulation.',
            lessons: [
                'Classes vs objects',
                'Creating and using classes',
                'Encapsulation',
                'Getters and setters',
                'Abstraction and coupling',
                'Constructors',
                'Constructor overloading',
                'Static fields and methods',
                'Project: modeling a bank account',
            ],
        },
        {
            title: 'Inheritance & Polymorphism',
            description: 'Reuse and extend behavior — and know when not to.',
            lessons: [
                'Inheritance basics',
                'The Object class (equals, hashCode, toString)',
                'Constructors and inheritance',
                'Access modifiers (public, private, protected)',
                'Method overriding',
                'Upcasting and downcasting',
                'Polymorphism in action',
                'Abstract classes and methods',
                'Final classes and methods',
                'The problem with deep inheritance hierarchies',
            ],
        },
        {
            title: 'Interfaces',
            description: 'Program against contracts to build loosely-coupled, testable code.',
            lessons: [
                'What interfaces are and why they matter',
                'Interfaces vs abstract classes',
                'Dependency injection: constructor injection',
                'Setter and method injection',
                'Interface segregation principle',
                'Default and static interface methods',
                'Project: a pluggable tax calculator',
            ],
        },
        {
            title: 'Exceptions',
            description: 'Handle failures without letting them corrupt your program.',
            lessons: [
                'Types of exceptions: checked, unchecked, errors',
                'try / catch / finally',
                'Catching multiple exception types',
                'try-with-resources',
                'Throwing exceptions',
                'Re-throwing and exception chaining',
                'Writing custom exceptions',
            ],
        },
        {
            title: 'Generics & Collections',
            description: 'The collections framework: the data structures you will use daily.',
            lessons: [
                'Why generics exist',
                'Generic classes and methods',
                'Bounded type parameters',
                'Wildcards (? extends / ? super)',
                'The Iterable and Collection interfaces',
                'List, ArrayList, and LinkedList',
                'Comparable vs Comparator',
                'Queue and Deque',
                'Set, HashSet, and TreeSet',
                'Map and HashMap',
                'Choosing the right collection',
            ],
        },
        {
            title: 'Lambdas & Streams',
            description: 'Functional-style Java for processing data elegantly.',
            lessons: [
                'Functional interfaces',
                'Lambda expressions',
                'Method references',
                'Consumer, Supplier, Function, Predicate',
                'Composing functions and predicates',
                'Creating streams',
                'Mapping and filtering',
                'Slicing: limit, skip, takeWhile',
                'Sorting and distinct',
                'Reducers and collectors',
                'Grouping and partitioning',
                'Primitive streams',
            ],
        },
        {
            title: 'Concurrency & Multithreading',
            description: 'Run work in parallel safely — from raw threads to executors.',
            lessons: [
                'Processes vs threads',
                'Starting and pausing threads',
                'Joining threads',
                'Race conditions and thread safety',
                'Confinement and immutability strategies',
                'Locks and synchronized',
                'volatile and visibility',
                'wait() and notify()',
                'The executor framework and thread pools',
                'Callables and Futures',
                'CompletableFuture essentials',
            ],
        },
        {
            title: 'The Java Ecosystem',
            description: 'Build tools, packages, and testing — how real Java projects are run.',
            lessons: [
                'Packages and imports',
                'Building with Maven (or Gradle)',
                'Managing dependencies',
                'Unit testing with JUnit',
                'Debugging in the IDE',
                'JARs and running your app anywhere',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'A complete console application using everything you learned.',
            lessons: [
                'Scoping the project (banking / inventory system)',
                'Designing the domain model',
                'Implementing services with interfaces',
                'Collections and streams for reporting',
                'Exception handling and validation',
                'Unit tests for core logic',
                'Packaging and final review',
            ],
        },
    ],
};
