import { Course } from '../types';

export const kotlin: Course = {
    id: 'kotlin',
    title: 'Kotlin Mastery',
    tagline: 'Modern JVM development — concise, null-safe, and Android-ready.',
    level: 'Beginner → Advanced',
    hours: 28,
    accent: '#7F52FF',
    badge: 'KT',
    modules: [
        {
            title: 'Getting Started',
            description: 'Kotlin, the JVM, and your first program.',
            lessons: [
                'What is Kotlin and why it won Android',
                'Kotlin and the JVM (and other targets)',
                'Installing IntelliJ IDEA',
                'Your first program: main and println',
                'Kotlin scripts and the REPL',
                'How Kotlin relates to Java',
            ],
        },
        {
            title: 'Variables & Types',
            description: 'val vs var, inference, and string templates.',
            lessons: [
                'val vs var (immutability first)',
                'Type inference and explicit types',
                'Numbers, Booleans, and Char',
                'Strings and string templates',
                'Raw strings',
                'Type conversion functions',
                'Nullable types: a first look',
            ],
        },
        {
            title: 'Control Flow',
            description: 'Expressions, not statements — Kotlin’s take on branching and loops.',
            lessons: [
                'if as an expression',
                'when: the supercharged switch',
                'Ranges (.., until, downTo, step)',
                'for loops',
                'while and do...while',
                'break and continue with labels',
                'Exercise: number classifier with when',
            ],
        },
        {
            title: 'Functions',
            description: 'Kotlin’s expressive function toolbox.',
            lessons: [
                'Declaring functions',
                'Default and named arguments',
                'Single-expression functions',
                'vararg',
                'Extension functions',
                'Infix functions',
                'Local functions',
                'Exercise: building a small DSL-style helper',
            ],
        },
        {
            title: 'Null Safety',
            description: 'The billion-dollar mistake, fixed at the type level.',
            lessons: [
                'Nullable vs non-null types',
                'Safe calls (?.)',
                'The Elvis operator (?:)',
                'Not-null assertion (!!) and when it is acceptable',
                'Safe casts (as?)',
                'let and null-handling idioms',
                'lateinit and lazy',
                'Platform types from Java',
            ],
        },
        {
            title: 'Classes & Objects',
            description: 'Data classes, sealed classes, and Kotlin’s concise OOP.',
            lessons: [
                'Classes and properties',
                'Primary and secondary constructors',
                'init blocks',
                'Custom getters and setters',
                'Data classes (equals, copy, destructuring)',
                'Enum classes',
                'Sealed classes and interfaces',
                'object declarations (singletons)',
                'Companion objects',
                'Nested and inner classes',
            ],
        },
        {
            title: 'Inheritance & Interfaces',
            description: 'Closed by default: Kotlin’s deliberate inheritance model.',
            lessons: [
                'open vs final classes',
                'Overriding methods and properties',
                'Abstract classes',
                'Interfaces with default implementations',
                'Visibility modifiers',
                'Class delegation (by)',
                'Smart casts and is checks',
            ],
        },
        {
            title: 'Collections & Lambdas',
            description: 'Functional collection processing — where Kotlin shines daily.',
            lessons: [
                'List, Set, Map: mutable vs read-only',
                'Lambda expressions and it',
                'Higher-order functions',
                'filter, map, flatMap',
                'reduce and fold',
                'groupBy, associateBy, partition',
                'Sequences and lazy evaluation',
                'Destructuring declarations',
                'Scope functions: let, run, with, apply, also',
                'Exercise: processing a sales dataset',
            ],
        },
        {
            title: 'Generics',
            description: 'Type-safe reusable code with variance done right.',
            lessons: [
                'Generic functions and classes',
                'Generic constraints',
                'Variance: in and out',
                'Star projections',
                'Reified type parameters with inline functions',
            ],
        },
        {
            title: 'Coroutines',
            description: 'Kotlin’s answer to async: structured concurrency.',
            lessons: [
                'Why coroutines: threads vs suspension',
                'suspend functions',
                'launch and async builders',
                'Structured concurrency and scopes',
                'Dispatchers and withContext',
                'Cancellation and timeouts',
                'Exception handling in coroutines',
                'Flow: cold asynchronous streams',
                'Channels overview',
            ],
        },
        {
            title: 'Java Interop & Ecosystem',
            description: 'Living happily on the JVM alongside Java.',
            lessons: [
                'Calling Java from Kotlin',
                'Calling Kotlin from Java (@JvmStatic, @JvmOverloads)',
                'Annotations and reflection basics',
                'Gradle with the Kotlin DSL',
                'Testing with JUnit and Kotest',
                'Ktlint and detekt',
            ],
        },
        {
            title: 'First Steps in Android (or Backend) + Capstone',
            description: 'Apply your Kotlin to a real platform, then build the capstone.',
            lessons: [
                'Tour: Android with Jetpack Compose',
                'Tour: backend with Ktor',
                'Choosing your capstone (task app / API)',
                'Capstone: modeling with data and sealed classes',
                'Capstone: coroutines for async work',
                'Capstone: tests, polish, and review',
            ],
        },
    ],
};
