import { CourseDefinition } from '../types';

export const laravel: CourseDefinition = {
    id: 'laravel',
    title: 'Laravel Mastery',
    tagline: 'The PHP framework with everything: Eloquent, Blade, queues, and joy.',
    level: 'Intermediate (PHP required)',
    hours: 26,
    accent: '#FF2D20',
    badge: 'LV',
    requires: ['php'],
    category: 'framework',
    stack: 'PHP',
    modules: [
        {
            title: 'Getting Started',
            description: 'Modern PHP tooling and a running Laravel app.',
            lessons: [
                'Why Laravel dominates PHP',
                'Installing (composer / Herd / Sail)',
                'Project structure tour',
                'artisan: your command-line companion',
                '.env and configuration',
                'The request lifecycle',
            ],
        },
        {
            title: 'Routing & Controllers',
            description: 'From URL to response.',
            lessons: [
                'Route basics and route files',
                'Route parameters and model binding',
                'Controllers and resource controllers',
                'Route groups and names',
                'Middleware: the concept',
                'Exercise: pages with clean routes',
            ],
        },
        {
            title: 'Blade Templates',
            description: 'Elegant server-rendered views.',
            lessons: [
                'Blade syntax: echoing and directives',
                'Layouts and sections',
                'Components (anonymous and class-based)',
                'Loops, conditionals, and @forelse',
                'Including assets with Vite',
                'Exercise: component-based layout',
            ],
        },
        {
            title: 'Database & Migrations',
            description: 'Schema as code.',
            lessons: [
                'Database configuration',
                'Migrations: create and modify tables',
                'Seeders',
                'Model factories (fake data)',
                'The query builder',
            ],
        },
        {
            title: 'Eloquent ORM',
            description: 'Laravel’s ActiveRecord — expressive and powerful.',
            lessons: [
                'Models and conventions',
                'CRUD with Eloquent',
                'Relationships: hasMany, belongsTo, belongsToMany',
                'Eager loading and the N+1 problem',
                'Scopes and accessors/mutators (casts)',
                'Collections: the hidden superpower',
                'Exercise: blog schema with relations',
            ],
        },
        {
            title: 'Forms & Validation',
            description: 'Safe input handling with almost no code.',
            lessons: [
                'CSRF and form basics',
                'The validate() method',
                'Form Request classes',
                'Displaying errors in Blade',
                'Old input and redirects',
                'File uploads and storage',
            ],
        },
        {
            title: 'Authentication & Authorization',
            description: 'From login pages to fine-grained permissions.',
            lessons: [
                'Starter kits (Breeze) — what they generate',
                'The Auth facade and guards',
                'Protecting routes with middleware',
                'Gates',
                'Policies for models',
                'Exercise: authors can edit only their posts',
            ],
        },
        {
            title: 'The Laravel Toolbox',
            description: 'Queues, mail, events — the features that sell Laravel.',
            lessons: [
                'File storage (local and S3-style)',
                'Sending mail (Mailables)',
                'Queues and jobs',
                'Events and listeners',
                'Task scheduling',
                'Notifications overview',
            ],
        },
        {
            title: 'Building APIs',
            description: 'Laravel as a JSON backend.',
            lessons: [
                'API routes and versioning',
                'API Resources (transformers)',
                'Sanctum: token auth for SPAs and mobile',
                'Rate limiting',
                'Exercise: JSON API for the blog',
            ],
        },
        {
            title: 'Testing',
            description: 'Pest-powered tests that read like sentences.',
            lessons: [
                'Pest setup and philosophy',
                'HTTP tests',
                'Database testing with RefreshDatabase',
                'Factories in tests',
                'Testing auth and policies',
            ],
        },
        {
            title: 'Deployment',
            description: 'Production-ready Laravel.',
            lessons: [
                'Optimization commands (config/route cache)',
                'Environment and secrets',
                'Queues and scheduler in production',
                'Deploying with Forge / a VPS',
                'Zero-downtime deploy concepts',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'A real product built the Laravel way.',
            lessons: [
                'Scoping: job board or booking system',
                'Migrations, models, factories',
                'Auth + policies',
                'Blade UI with components',
                'API endpoints with Sanctum',
                'Tests and deploy',
            ],
        },
    ],
};
