import { CourseDefinition } from '../types';

export const nextjs: CourseDefinition = {
    id: 'nextjs',
    title: 'Next.js: Full-Stack React',
    tagline: 'Production React with server components, data, and deployment built in.',
    level: 'Intermediate (React required)',
    hours: 22,
    accent: '#e5e5e5',
    badge: 'N',
    category: 'framework',
    stack: 'JavaScript',
    modules: [
        {
            title: 'Getting Started',
            description: 'Why Next.js exists and a tour of a fresh project.',
            lessons: [
                'What Next.js adds on top of React',
                'create-next-app and project anatomy',
                'The App Router directory structure',
                'Dev server, build, and start',
                'Fast Refresh and debugging',
            ],
        },
        {
            title: 'Routing with the App Router',
            description: 'File-system routing: pages, layouts, and everything between.',
            lessons: [
                'Pages and file conventions',
                'Layouts and nested layouts',
                'Navigating with Link and useRouter',
                'Dynamic routes ([id])',
                'Catch-all routes',
                'Route groups and private folders',
                'loading.tsx and error.tsx',
                'not-found and redirects',
            ],
        },
        {
            title: 'Server & Client Components',
            description: 'The mental model that makes or breaks Next.js developers.',
            lessons: [
                'What React Server Components are',
                "The 'use client' directive",
                'What each kind can and cannot do',
                'Composition: passing server children into client components',
                'Where state, effects, and event handlers live',
                'Common RSC mistakes and their error messages',
            ],
        },
        {
            title: 'Data Fetching',
            description: 'Fetch on the server by default — with caching you control.',
            lessons: [
                'Fetching in server components (async/await)',
                'Request caching and revalidation',
                'revalidate options and dynamic rendering',
                'Parallel vs sequential fetching',
                'Streaming with Suspense',
                'Fetching in client components (when needed)',
            ],
        },
        {
            title: 'Mutations with Server Actions',
            description: 'Write to your database without hand-rolled API endpoints.',
            lessons: [
                "'use server' and defining actions",
                'Forms with server actions',
                'useActionState and pending UI',
                'Validation with Zod inside actions',
                'revalidatePath and revalidateTag',
                'Optimistic updates',
            ],
        },
        {
            title: 'Styling, Fonts & Images',
            description: 'The built-ins that make sites fast by default.',
            lessons: [
                'Global CSS and CSS Modules',
                'Tailwind CSS setup',
                'next/image: optimized images',
                'next/font: zero-layout-shift fonts',
                'Metadata API and favicons',
            ],
        },
        {
            title: 'Route Handlers & Middleware',
            description: 'When you do need HTTP endpoints and edge logic.',
            lessons: [
                'route.ts: GET/POST handlers',
                'Reading request data, returning responses',
                'Middleware: rewrites, redirects, auth checks',
                'Environment variables (server vs NEXT_PUBLIC)',
                'CORS and webhooks',
            ],
        },
        {
            title: 'Database & Auth',
            description: 'The full-stack part: persist data and know your user.',
            lessons: [
                'Choosing an ORM: Prisma or Drizzle',
                'Schema, migrations, and queries',
                'Querying from server components and actions',
                'Auth.js (NextAuth) setup',
                'Sessions in server components',
                'Protecting routes and actions',
            ],
        },
        {
            title: 'Rendering Strategies & SEO',
            description: 'Static, dynamic, and everything Next.js can pre-build.',
            lessons: [
                'Static vs dynamic rendering (and how Next decides)',
                'ISR: incremental static regeneration',
                'generateStaticParams',
                'SEO: metadata, sitemaps, Open Graph images',
                'When to use static export',
            ],
        },
        {
            title: 'Deployment & Production',
            description: 'Ship it and keep it healthy.',
            lessons: [
                'Deploying to Vercel',
                'Self-hosting with Docker/Node',
                'Environment configuration per stage',
                'Caching in production (what to watch)',
                'Analytics and monitoring basics',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'A full-stack app: database, auth, and a public deploy.',
            lessons: [
                'Scoping: a job board or booking app',
                'Data model and schema',
                'Routes, layouts, and server components',
                'Server actions for all mutations',
                'Auth and role-based access',
                'SEO pass and performance check',
                'Deploy and postmortem',
            ],
        },
    ],
};
