import { Course } from '../types';

export const nodeExpress: Course = {
    id: 'node-express',
    title: 'Node.js & Express',
    tagline: 'Backend JavaScript: REST APIs, databases, auth, and deployment.',
    level: 'Intermediate (JavaScript required)',
    hours: 26,
    accent: '#339933',
    badge: 'NODE',
    category: 'framework',
    stack: 'JavaScript',
    modules: [
        {
            title: 'Getting Started with Node',
            description: 'JavaScript outside the browser.',
            lessons: [
                'What Node.js is (V8 + libuv)',
                'Installing Node and using npm',
                'Running scripts and the Node REPL',
                'Module systems: CommonJS vs ES Modules',
                'package.json and npm scripts',
                'nodemon / --watch for development',
            ],
        },
        {
            title: 'Node Fundamentals',
            description: 'The runtime model and core modules.',
            lessons: [
                'The event loop explained',
                'Blocking vs non-blocking code',
                'Global objects (process, __dirname)',
                'fs: files and directories',
                'path and os modules',
                'Buffers and streams (first look)',
                'EventEmitter',
            ],
        },
        {
            title: 'Asynchronous Patterns',
            description: 'From callbacks to clean async/await.',
            lessons: [
                'Callback style and error-first callbacks',
                'Promises and fs/promises',
                'async/await in Node',
                'Handling errors properly',
                'Running work in parallel (Promise.all)',
                'Exercise: async file processor',
            ],
        },
        {
            title: 'Express Basics',
            description: 'The de-facto web framework for Node.',
            lessons: [
                'Creating a server with Express',
                'Routes and HTTP methods',
                'Route params and query strings',
                'Reading JSON bodies',
                'What middleware really is',
                'Serving static files',
                'Exercise: first mini API',
            ],
        },
        {
            title: 'Building RESTful APIs',
            description: 'Professional API structure from day one.',
            lessons: [
                'REST conventions: resources and verbs',
                'CRUD endpoints for a resource',
                'Input validation with Zod',
                'Error-handling middleware',
                'Routers, controllers, and services (project structure)',
                'Status codes done right',
                'Exercise: courses API (in-memory)',
            ],
        },
        {
            title: 'Working with a Database',
            description: 'Persist data with MongoDB (and see the SQL path).',
            lessons: [
                'MongoDB and Mongoose setup',
                'Schemas and models',
                'CRUD operations',
                'Validation at the model layer',
                'Relationships: references vs embedding',
                'The SQL alternative: Prisma in 20 minutes',
            ],
        },
        {
            title: 'Authentication & Authorization',
            description: 'Who are you, and what may you do?',
            lessons: [
                'Hashing passwords with bcrypt',
                'Registration and login endpoints',
                'JSON Web Tokens',
                'Auth middleware',
                'Roles and permissions',
                'Refresh tokens and logout strategies',
            ],
        },
        {
            title: 'Production Concerns',
            description: 'The unglamorous parts that make an API real.',
            lessons: [
                'Configuration and environment variables',
                'Logging (pino/winston)',
                'CORS',
                'Security headers with helmet',
                'Rate limiting',
                'File uploads (multer)',
                'Graceful shutdown',
            ],
        },
        {
            title: 'Testing',
            description: 'Test the API surface, not the internals.',
            lessons: [
                'Vitest/Jest setup for Node',
                'Integration tests with supertest',
                'Test database strategies',
                'Mocking external services',
                'CI basics',
            ],
        },
        {
            title: 'Deployment',
            description: 'From localhost to a public URL.',
            lessons: [
                'Preparing for production (NODE_ENV, builds)',
                'Docker for Node apps',
                'Deploying to a VPS/Render/Railway',
                'Process managers (PM2)',
                'Monitoring and health checks',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'A complete, documented, deployed REST API.',
            lessons: [
                'Scoping: bookings or e-commerce API',
                'Data model and routes design',
                'Auth + roles implementation',
                'Validation and error contract',
                'Test suite',
                'Dockerize and deploy',
                'API docs with OpenAPI/Swagger',
            ],
        },
    ],
};
