import { CourseDefinition } from '../types';

export const php: CourseDefinition = {
    id: 'php',
    title: 'PHP Mastery',
    tagline: 'Modern PHP for the web — from first script to Laravel-ready.',
    level: 'Beginner → Advanced',
    hours: 26,
    accent: '#777BB4',
    badge: 'PHP',
    modules: [
        {
            title: 'Getting Started',
            description: 'Modern PHP (it is not 2005 anymore) and how the web request flows.',
            lessons: [
                'What PHP is today (8.x) and where it runs',
                'Installing PHP and Composer',
                'The built-in dev server',
                'Your first script',
                'How a PHP web request works',
                'PHP tags and embedding in HTML vs pure PHP files',
                'echo, print, var_dump',
            ],
        },
        {
            title: 'Basics',
            description: 'Variables, types, and strict typing.',
            lessons: [
                'Variables',
                'Data types and gettype',
                'Strings: single vs double quotes, heredoc',
                'String interpolation and concatenation',
                'Numbers and arithmetic',
                'Constants and define vs const',
                'Type juggling and declare(strict_types=1)',
                'Operators and comparisons (== vs ===)',
            ],
        },
        {
            title: 'Control Flow',
            description: 'Branching, loops, and template-friendly syntax.',
            lessons: [
                'if / elseif / else',
                'switch',
                'The match expression (PHP 8)',
                'Ternary and null coalescing (??)',
                'while, do...while, for',
                'foreach',
                'break and continue',
                'Alternative syntax for templates',
            ],
        },
        {
            title: 'Arrays',
            description: 'PHP’s do-everything data structure, mastered.',
            lessons: [
                'Indexed and associative arrays',
                'Multidimensional arrays',
                'Adding, removing, and checking items',
                'array_map, array_filter, array_reduce',
                'Sorting: sort, usort, ksort family',
                'Destructuring and the spread operator',
                'array_keys, array_values, in_array, array_search',
                'Exercise: shopping cart calculations',
            ],
        },
        {
            title: 'Functions',
            description: 'Typed, modern PHP functions.',
            lessons: [
                'Defining functions',
                'Type declarations and return types',
                'Default and named arguments',
                'Variadic functions',
                'Anonymous functions and closures (use)',
                'Arrow functions',
                'Nullable and union types',
                'callable and first-class callables',
            ],
        },
        {
            title: 'Forms, HTTP & Sessions',
            description: 'The web fundamentals every PHP developer must own.',
            lessons: [
                'GET vs POST and superglobals',
                'Reading form input safely',
                'Validating and sanitizing (filter_var)',
                'File uploads',
                'Cookies',
                'Sessions',
                'Headers and redirects',
                'Security: XSS and output escaping',
                'Security: CSRF tokens',
                'Project: contact form with validation',
            ],
        },
        {
            title: 'Object-Oriented PHP',
            description: 'Modern OOP: promotion, traits, enums, and autoloading.',
            lessons: [
                'Classes, properties, methods',
                'Constructor property promotion',
                'Visibility: public, private, protected',
                'Static properties and methods',
                'Inheritance',
                'Abstract classes and interfaces',
                'Traits',
                'Enums (PHP 8.1)',
                'readonly properties',
                'Magic methods (__get, __call, __toString)',
                'Namespaces',
                'Autoloading with PSR-4',
            ],
        },
        {
            title: 'Errors & Exceptions',
            description: 'A coherent strategy for when things go wrong.',
            lessons: [
                'Error levels and error_reporting',
                'Exceptions: try / catch / finally',
                'The Throwable hierarchy',
                'Custom exceptions',
                'Global handlers and logging',
                'Errors in development vs production',
            ],
        },
        {
            title: 'Databases with PDO',
            description: 'Safe database access — SQL injection ends here.',
            lessons: [
                'Connecting with PDO and DSNs',
                'Why prepared statements (SQL injection demo)',
                'SELECT with bound parameters',
                'INSERT, UPDATE, DELETE',
                'Fetch modes',
                'Transactions',
                'A simple repository class',
                'Project: notes app backed by MySQL/SQLite',
            ],
        },
        {
            title: 'Composer & the Ecosystem',
            description: 'Packages, standards, and professional tooling.',
            lessons: [
                'composer init and require',
                'Autoloading your own code',
                'Popular packages (guzzle, dotenv, carbon)',
                'PSR standards overview',
                'Testing with PHPUnit',
                'Static analysis with PHPStan',
                'Code style with PHP-CS-Fixer',
            ],
        },
        {
            title: 'Building a Mini MVC App',
            description: 'Understand what frameworks do by building the core yourself.',
            lessons: [
                'Front controller and routing',
                'Controllers',
                'Views and a tiny template system',
                'Models and the database layer',
                'Handling POST actions',
                'Project structure recap',
            ],
        },
        {
            title: 'Laravel First Steps + Capstone',
            description: 'The professional PHP framework, then your final project.',
            lessons: [
                'Laravel overview: artisan, routing, Blade',
                'Eloquent ORM basics',
                'Migrations',
                'Capstone: CRUD app (mini blog) — plan',
                'Capstone: build it (framework-free or Laravel)',
                'Capstone: security & polish review',
            ],
        },
    ],
};
