import { CourseDefinition } from '../types';

export const postgresql: CourseDefinition = {
    id: 'postgresql',
    title: 'PostgreSQL In Depth',
    tagline: 'Go beyond generic SQL: JSONB, window functions, indexing, and tuning.',
    level: 'Intermediate → Advanced (SQL required)',
    hours: 22,
    accent: '#336791',
    badge: 'PG',
    requires: ['psql'],
    modules: [
        {
            title: 'Getting Started with Postgres',
            description: 'Why Postgres, plus psql — the tool you will live in.',
            lessons: [
                'Why PostgreSQL (vs MySQL and others)',
                'Installing PostgreSQL',
                'psql essentials: \\l, \\c, \\dt, \\d',
                'pgAdmin and GUI clients',
                'Creating databases and users',
                'Loading a sample database',
                'pg_dump and restore basics',
            ],
        },
        {
            title: 'Postgres Data Types',
            description: 'The rich type system that sets Postgres apart.',
            lessons: [
                'Numeric types, serial, and identity columns',
                'text vs varchar (the honest answer)',
                'timestamp vs timestamptz — always know the difference',
                'date, time, and interval',
                'boolean',
                'UUID',
                'Arrays',
                'JSON vs JSONB',
                'Range types',
                'Enums and custom domains',
            ],
        },
        {
            title: 'Schema Design & Constraints',
            description: 'Let the database enforce your rules.',
            lessons: [
                'Schemas and search_path',
                'Primary keys: serial vs identity vs UUID',
                'Foreign keys and ON DELETE behaviors',
                'UNIQUE constraints',
                'CHECK constraints',
                'NOT NULL and defaults',
                'Generated columns',
                'Exercise: designing a multi-tenant schema',
            ],
        },
        {
            title: 'Advanced Querying',
            description: 'CTEs, window functions, and the queries that impress in interviews.',
            lessons: [
                'DISTINCT ON',
                'Common Table Expressions (WITH)',
                'Recursive CTEs (trees and graphs)',
                'Window functions: ROW_NUMBER, RANK, DENSE_RANK',
                'LAG and LEAD',
                'Window frames and running totals',
                'PARTITION BY',
                'LATERAL joins',
                'GROUPING SETS, CUBE, ROLLUP',
                'Exercise: top-N per group',
            ],
        },
        {
            title: 'JSONB in Practice',
            description: 'Document flexibility inside a relational database.',
            lessons: [
                'Storing JSONB',
                'Operators: ->, ->>, #>, @>',
                'jsonb functions (jsonb_build_object, jsonb_agg)',
                'Querying nested structures',
                'Updating JSONB (jsonb_set, ||, -)',
                'Indexing JSONB with GIN',
                'When to use JSONB vs normal columns',
            ],
        },
        {
            title: 'Full-Text Search',
            description: 'Built-in search without an extra service.',
            lessons: [
                'tsvector and tsquery',
                'to_tsvector and to_tsquery',
                'Ranking results (ts_rank)',
                'Dictionaries and configurations',
                'Indexes for full-text search',
                'Trigram similarity (pg_trgm) as an alternative',
                'Exercise: searching articles',
            ],
        },
        {
            title: 'Functions & PL/pgSQL',
            description: 'Server-side logic with Postgres’s procedural language.',
            lessons: [
                'SQL functions',
                'PL/pgSQL blocks and variables',
                'Control flow: IF, CASE, loops',
                'RETURNS TABLE and SETOF',
                'Exception handling',
                'Stored procedures and transactions (CALL)',
                'SECURITY DEFINER and safety',
            ],
        },
        {
            title: 'Triggers',
            description: 'Automatic reactions to data changes, done responsibly.',
            lessons: [
                'Trigger functions',
                'BEFORE vs AFTER triggers',
                'Row-level vs statement-level',
                'NEW and OLD',
                'Audit-log pattern with triggers',
                'updated_at automation',
                'When triggers become a trap',
            ],
        },
        {
            title: 'Indexes Deep-Dive',
            description: 'Read query plans and choose the right index every time.',
            lessons: [
                'B-tree indexes (the default)',
                'Multicolumn indexes and column order',
                'Partial indexes',
                'Expression indexes',
                'GIN, GiST, BRIN, and Hash: when each wins',
                'EXPLAIN and EXPLAIN ANALYZE',
                'Reading query plans (seq scan vs index scan)',
                'Finding unused indexes (pg_stat_user_indexes)',
            ],
        },
        {
            title: 'Transactions, MVCC & Locking',
            description: 'How Postgres achieves concurrency — and what it costs.',
            lessons: [
                'MVCC explained',
                'Isolation levels in Postgres',
                'Explicit locking (SELECT FOR UPDATE)',
                'Advisory locks',
                'Deadlocks: detecting and avoiding',
                'VACUUM and autovacuum',
                'Table bloat and how to spot it',
            ],
        },
        {
            title: 'Roles & Security',
            description: 'Lock down who can see and change what.',
            lessons: [
                'Roles vs users',
                'GRANT and REVOKE',
                'Object ownership',
                'Row-Level Security policies',
                'pg_hba.conf and connection security',
                'Least privilege for application users',
            ],
        },
        {
            title: 'Administration Basics',
            description: 'Keep a production database alive and healthy.',
            lessons: [
                'postgresql.conf: the settings that matter',
                'Backups: pg_dump vs pg_basebackup',
                'Point-in-time recovery (concept)',
                'Replication overview (streaming, logical)',
                'Monitoring with pg_stat_activity',
                'Useful extensions: pgcrypto, uuid-ossp, PostGIS (tour)',
            ],
        },
        {
            title: 'Performance Tuning Capstone',
            description: 'Take a slow database and make it fast — with measurements.',
            lessons: [
                'Designing the schema for the project',
                'Loading realistic data volumes',
                'Finding slow queries (pg_stat_statements)',
                'EXPLAIN ANALYZE before and after',
                'Adding the right indexes',
                'Rewriting problem queries',
                'Final report: measured improvements',
            ],
        },
    ],
};
