import { CourseDefinition } from '../types';
import * as ex from './exercises/python';

export const python: CourseDefinition = {
    id: 'python',
    title: 'Python Mastery',
    tagline: 'From your first "Hello World" to shipping real Python projects.',
    level: 'Beginner → Advanced',
    hours: 30,
    accent: '#3776AB',
    badge: 'PY',
    requires: ['python'],
    modules: [
        {
            title: 'Getting Started',
            description: 'Set up Python the right way and understand what actually happens when your code runs.',
            lessons: [
                'What is Python and what can you build with it',
                'Installing Python 3 on your machine',
                { title: 'Your first program: Hello World', exercise: ex.helloWorld },
                'How Python code is executed (interpreter, bytecode)',
                'Setting up your editor and Python extensions',
                'Linting and formatting with PEP 8',
                'Running scripts vs the interactive REPL',
                'Comments and writing readable code',
            ],
        },
        {
            title: 'Primitive Types & Variables',
            description: 'Master the building blocks: variables, strings, and numbers.',
            lessons: [
                'Variables and how Python stores them',
                'Variable naming conventions',
                { title: 'Strings and indexing/slicing', exercise: ex.slicing },
                'Escape sequences',
                { title: 'Formatted strings (f-strings)', exercise: ex.fStrings },
                { title: 'Essential string methods', exercise: ex.stringMethods },
                'Numbers: int, float, complex',
                { title: 'Arithmetic operators and augmented assignment', exercise: ex.arithmetic },
                'Working with the math module',
                { title: 'Type conversion and type()', exercise: ex.typeConversion },
            ],
        },
        {
            title: 'Control Flow',
            description: 'Teach your programs to make decisions and repeat work.',
            lessons: [
                'Comparison operators',
                { title: 'Conditional statements (if / elif / else)', exercise: ex.ifElif },
                'Ternary (conditional) expressions',
                { title: 'Logical operators (and / or / not)', exercise: ex.leapYear },
                'Short-circuit evaluation',
                'Chaining comparison operators',
                { title: 'For loops and range()', exercise: ex.forRange },
                'for..else',
                'Nested loops',
                { title: 'While loops and infinite loops', exercise: ex.whileLoop },
                'Iterables and the iteration protocol',
                { title: 'Exercise: FizzBuzz and a guessing game', exercise: ex.fizzBuzz },
            ],
        },
        {
            title: 'Functions',
            description: 'Write reusable, clean functions like a professional.',
            lessons: [
                'Defining and calling functions',
                'Parameters vs arguments',
                'Keyword arguments',
                { title: 'Default argument values', exercise: ex.defaultArgs },
                { title: 'Returning values (and returning None)', exercise: ex.returningNone },
                '*args: variable-length arguments',
                '**kwargs: keyword argument packing',
                'Scope: local, global, and the LEGB rule',
                'Debugging functions step by step',
                { title: 'Exercise: reusable Fibonacci and validation helpers', exercise: ex.fibonacci },
            ],
        },
        {
            title: 'Data Structures',
            description: 'Lists, tuples, sets, and dictionaries — plus the idioms that make Python famous.',
            lessons: [
                'Lists: creating and accessing items',
                'List unpacking',
                'Adding, removing, and finding items',
                'Sorting lists and the key parameter',
                'Lambda functions',
                'Map and filter',
                { title: 'List comprehensions', exercise: ex.listComprehension },
                'Zip',
                'Stacks and queues (deque)',
                'Tuples and swapping variables',
                'Sets and set operations',
                'Dictionaries and dictionary comprehensions',
                'Generator expressions',
                'The unpacking operator (* and **)',
                { title: 'Exercise: word frequency counter', exercise: ex.wordFrequency },
            ],
        },
        {
            title: 'Exceptions',
            description: 'Handle errors gracefully instead of crashing.',
            lessons: [
                'What exceptions are and reading tracebacks',
                'Handling exceptions with try / except',
                'Handling different exception types',
                'Cleaning up with finally',
                'The with statement and context managers',
                'Raising exceptions',
                'The cost of raising exceptions (EAFP vs LBYL)',
            ],
        },
        {
            title: 'Classes & Object-Oriented Programming',
            description: 'Model real-world concepts with classes, inheritance, and magic methods.',
            lessons: [
                'Classes vs objects (instances)',
                'Creating your first class',
                'Constructors (__init__)',
                'Instance vs class attributes',
                'Instance, class, and static methods',
                'Magic methods (__str__, __repr__, __eq__)',
                'Comparing objects and arithmetic operators',
                'Making custom containers',
                'Private members and name mangling',
                'Properties (@property)',
                'Inheritance and method overriding',
                'Multiple inheritance and MRO',
                'Abstract base classes',
                'Duck typing',
                'Extending built-in types',
                'Data classes (@dataclass)',
            ],
        },
        {
            title: 'Modules & Packages',
            description: 'Organize code across files and packages like real projects do.',
            lessons: [
                'Creating and importing modules',
                'Compiled Python files (__pycache__)',
                'The module search path',
                'Packages and __init__.py',
                'Sub-packages',
                'Intra-package references',
                'The dir() function',
                'Executing modules as scripts (__name__ == "__main__")',
            ],
        },
        {
            title: 'The Standard Library',
            description: 'The batteries included: files, dates, JSON, SQLite, and more.',
            lessons: [
                'Working with paths (pathlib)',
                'Working with directories and files',
                'Zip files',
                'CSV files',
                'JSON',
                'SQLite databases',
                'Timestamps, datetimes, and time deltas',
                'Generating random values',
                'Command-line arguments (sys.argv, argparse)',
                'Running external programs (subprocess)',
                'Sending emails and templates',
            ],
        },
        {
            title: 'pip, Virtual Environments & Packaging',
            description: 'Manage dependencies and share your code with the world.',
            lessons: [
                'The Python Package Index (PyPI)',
                'Installing packages with pip',
                'Virtual environments (venv)',
                'Managing dependencies (requirements.txt)',
                'Project layout for a publishable package',
                'Publishing your own package',
                'Docstrings and generating docs with pydoc',
            ],
        },
        {
            title: 'Popular Libraries',
            description: 'A guided tour of the libraries professionals reach for daily.',
            lessons: [
                'Calling web APIs with requests',
                'Web scraping with BeautifulSoup',
                'Automating Excel spreadsheets (openpyxl)',
                'Working with PDFs and images (Pillow)',
                'NumPy arrays: your first taste of data science',
                'A first look at pandas DataFrames',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'Put everything together: design, build, and package a complete CLI application.',
            lessons: [
                'Choosing and scoping the project (expense tracker CLI)',
                'Designing the data model and file structure',
                'Building the core features',
                'Persisting data with JSON or SQLite',
                'Handling errors and edge cases',
                'Writing tests with pytest',
                'Packaging and sharing your app',
                'Ideas to extend it further',
            ],
        },
    ],
};
