import { CourseDefinition } from '../types';

export const react: CourseDefinition = {
    id: 'react',
    title: 'React Mastery',
    tagline: 'The most in-demand UI library — components, hooks, and real apps.',
    level: 'Intermediate (JavaScript required)',
    hours: 28,
    accent: '#61DAFB',
    badge: 'R',
    requires: ['node'],
    category: 'framework',
    stack: 'JavaScript',
    modules: [
        {
            title: 'Getting Started',
            description: 'What React is, why it took over, and a modern project setup.',
            lessons: [
                'What is React and the component mental model',
                'Single-page apps vs traditional pages',
                'Creating a project with Vite',
                'Project structure tour',
                'JSX: JavaScript + markup',
                'Your first component',
                'React Developer Tools',
            ],
        },
        {
            title: 'Components',
            description: 'Build UIs from small, reusable pieces.',
            lessons: [
                'Function components',
                'JSX rules (fragments, expressions, attributes)',
                'Props and passing data down',
                'The children prop',
                'Conditional rendering',
                'Rendering lists and the key prop',
                'Styling options: CSS modules, inline, Tailwind',
                'Exercise: a reusable Card and Badge',
            ],
        },
        {
            title: 'State & Events',
            description: 'Make components interactive with useState.',
            lessons: [
                'Handling events',
                'useState: your first hook',
                'State vs props',
                'Updating objects and arrays immutably',
                'Multiple state variables vs one object',
                'Lifting state up',
                'Sharing state between components',
                'Exercise: interactive cart quantity picker',
            ],
        },
        {
            title: 'Building Forms',
            description: 'Controlled inputs and professional validation.',
            lessons: [
                'Controlled components',
                'Handling form submission',
                'Validating manually (and why it gets messy)',
                'React Hook Form',
                'Schema validation with Zod',
                'Showing errors well',
                'Exercise: signup form with full validation',
            ],
        },
        {
            title: 'Effects & Data Fetching',
            description: 'Talk to the outside world without foot-guns.',
            lessons: [
                'What effects are for (and what they are not)',
                'useEffect and the dependency array',
                'Cleanup functions',
                'Fetching data with fetch/axios',
                'Loading and error states',
                'Race conditions and cancellation',
                'Extracting a custom useFetch hook',
            ],
        },
        {
            title: 'Advanced State Management',
            description: 'When useState is not enough: reducers, context, and query caches.',
            lessons: [
                'useReducer',
                'Prop drilling and Context',
                'When context hurts performance',
                'Server state vs client state',
                'TanStack Query: caching, refetching, mutations',
                'Zustand for global client state',
                'Choosing the right tool',
            ],
        },
        {
            title: 'Routing',
            description: 'Multi-page experiences with React Router.',
            lessons: [
                'Setting up React Router',
                'Routes and links',
                'Route parameters',
                'Nested routes and layouts',
                'Programmatic navigation',
                'Protected routes',
                '404 and error pages',
            ],
        },
        {
            title: 'Hooks Deep Dive',
            description: 'The rest of the toolbox — and the rules that keep it working.',
            lessons: [
                'Rules of hooks (and why they exist)',
                'useRef: DOM access and mutable values',
                'useMemo',
                'useCallback',
                'Custom hooks: patterns and naming',
                'useLayoutEffect vs useEffect',
                'Exercise: useLocalStorage and useDebounce',
            ],
        },
        {
            title: 'Performance',
            description: 'Understand re-renders before you optimize them.',
            lessons: [
                'The re-render mental model',
                'Profiling with React DevTools',
                'React.memo',
                'Code splitting with lazy and Suspense',
                'List virtualization overview',
                'Common performance myths',
            ],
        },
        {
            title: 'TypeScript with React',
            description: 'Typed components, props, and hooks.',
            lessons: [
                'Typing props and children',
                'Typing state and events',
                'Typing custom hooks',
                'Generic components',
                'Common TS+React errors decoded',
            ],
        },
        {
            title: 'Testing',
            description: 'Confidence via tests that resemble real usage.',
            lessons: [
                'Vitest + React Testing Library setup',
                'Rendering and querying like a user',
                'Simulating interaction with user-event',
                'Mocking API calls (MSW)',
                'What to test (and what not to)',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'A polished, deployed React application.',
            lessons: [
                'Scoping: an issue tracker or storefront',
                'Project structure and routing skeleton',
                'Data layer with TanStack Query',
                'Forms and mutations',
                'Auth flow',
                'Polish: loading, errors, empty states',
                'Deploying to Netlify/Vercel',
            ],
        },
    ],
};
