import { Course } from '../types';

export const ruby: Course = {
    id: 'ruby',
    title: 'Ruby Mastery',
    tagline: 'A language optimized for programmer happiness — and the road to Rails.',
    level: 'Beginner → Advanced',
    hours: 24,
    accent: '#CC342D',
    badge: 'RB',
    modules: [
        {
            title: 'Getting Started',
            description: 'Ruby’s philosophy and your interactive playground.',
            lessons: [
                'The Ruby philosophy: everything is an object',
                'Installing Ruby (rbenv / installer)',
                'irb: the interactive console',
                'Your first script and running .rb files',
                'puts, print, and p',
                'Getting user input with gets',
                'Comments and style basics',
            ],
        },
        {
            title: 'Basics',
            description: 'Variables, strings, symbols, and numbers.',
            lessons: [
                'Variables and naming',
                'Numbers and arithmetic',
                'Strings and interpolation',
                'Common string methods',
                'Symbols and when to use them',
                'Booleans, nil, and truthiness',
                'Constants',
                'Type conversion (to_i, to_s, to_f)',
            ],
        },
        {
            title: 'Control Flow',
            description: 'Ruby’s expressive conditionals and loops.',
            lessons: [
                'if / elsif / else',
                'unless',
                'Statement modifiers (do_it if condition)',
                'case / when',
                'Ternary operator',
                'while and until',
                'loop, break, and next',
                'Exercise: number guessing game',
            ],
        },
        {
            title: 'Methods',
            description: 'Defining behavior with Ruby’s flexible method system.',
            lessons: [
                'Defining methods and implicit return',
                'Default arguments',
                'Keyword arguments',
                'Splat (*) and double splat (**)',
                'Predicate and bang method conventions',
                'Blocks: a first look with yield',
            ],
        },
        {
            title: 'Collections',
            description: 'Arrays, hashes, and the iteration style Ruby is famous for.',
            lessons: [
                'Arrays: creating and accessing',
                'Essential array methods',
                'Hashes and symbol keys',
                'Iterating with each',
                'map, select, reject',
                'reduce / inject',
                'Ranges',
                'Nested collections',
                'Sorting with sort_by',
                'Exercise: gradebook processor',
            ],
        },
        {
            title: 'Blocks, Procs & Lambdas',
            description: 'Ruby’s closures in depth — the feature behind its elegance.',
            lessons: [
                'yield and block_given?',
                'Passing blocks explicitly (&block)',
                'Procs',
                'Lambdas and how they differ from procs',
                'Closures and captured variables',
                'The &:symbol idiom',
                'Writing methods that take blocks',
            ],
        },
        {
            title: 'Object-Oriented Ruby',
            description: 'Classes, attributes, and Ruby’s object model.',
            lessons: [
                'Classes and instances',
                'initialize and instance variables',
                'attr_reader, attr_writer, attr_accessor',
                'Instance methods and self',
                'Class methods and class variables',
                'Method visibility: private and protected',
                'Comparing objects (==, equal?, eql?)',
                'to_s and inspect',
            ],
        },
        {
            title: 'Inheritance, Modules & Mixins',
            description: 'Sharing behavior the Ruby way.',
            lessons: [
                'Inheritance and super',
                'Modules as namespaces',
                'Mixins with include and extend',
                'Comparable and Enumerable: instant power',
                'The method lookup chain (ancestors)',
                'Duck typing',
                'Exercise: building a Playlist with Enumerable',
            ],
        },
        {
            title: 'Error Handling & Files',
            description: 'Failing gracefully and working with data files.',
            lessons: [
                'begin / rescue / ensure',
                'raise and custom error classes',
                'retry',
                'Reading and writing files',
                'Working with JSON',
                'Working with CSV',
                'YAML for configuration',
            ],
        },
        {
            title: 'The Ruby Ecosystem',
            description: 'Gems, Bundler, testing, and code quality.',
            lessons: [
                'RubyGems and installing gems',
                'Bundler and the Gemfile',
                'rake tasks',
                'Testing with Minitest',
                'Testing with RSpec (overview)',
                'RuboCop',
                'Debugging with debug / pry',
            ],
        },
        {
            title: 'Metaprogramming & Stdlib Tour',
            description: 'A taste of Ruby’s dynamic superpowers — used responsibly.',
            lessons: [
                'send and public_send',
                'define_method',
                'method_missing (and respond_to_missing?)',
                'Struct and OpenStruct',
                'ERB templates',
                'net/http: calling APIs',
            ],
        },
        {
            title: 'Rails First Steps + Capstone',
            description: 'See where Ruby shines professionally, then build your own project.',
            lessons: [
                'Rails and MVC: the big picture',
                'Scaffolding a tiny Rails app',
                'Routes, controllers, views, models',
                'Capstone: CLI app (library manager) — design',
                'Capstone: implement with OOP and files',
                'Capstone: tests and final review',
            ],
        },
    ],
};
