import { CourseDefinition } from '../types';

export const rust: CourseDefinition = {
    id: 'rust',
    title: 'Rust Mastery',
    tagline: 'Fearless systems programming — ownership, lifetimes, and zero-cost abstractions.',
    level: 'Beginner → Advanced',
    hours: 40,
    accent: '#DEA584',
    badge: 'RS',
    modules: [
        {
            title: 'Getting Started',
            description: 'Install Rust and meet cargo, the best build tool you have ever used.',
            lessons: [
                'Why Rust: safety without garbage collection',
                'Installing with rustup',
                'Hello World and rustc',
                'cargo new, build, run, check',
                'Crates and crates.io',
                'rust-analyzer and editor setup',
            ],
        },
        {
            title: 'Variables & Types',
            description: 'Immutability by default and an expression-based language.',
            lessons: [
                'Variables and mutability (mut)',
                'Shadowing',
                'Scalar types: integers, floats, bool, char',
                'Compound types: tuples and arrays',
                'Constants and statics',
                'Functions, statements vs expressions',
                'Comments and rustdoc comments',
            ],
        },
        {
            title: 'Control Flow',
            description: 'Branching and looping — everything is an expression.',
            lessons: [
                'if as an expression',
                'loop, while, and for',
                'Ranges',
                'match: a first look',
                'if let and while let',
                'Exercise: temperature converter and Fibonacci',
            ],
        },
        {
            title: 'Ownership',
            description: 'The concept that makes Rust Rust — learned properly, once.',
            lessons: [
                'The three ownership rules',
                'Move semantics',
                'Clone and Copy',
                'Ownership and functions',
                'References and borrowing',
                'Mutable references and the aliasing rule',
                'Dangling references (and why they cannot compile)',
                'Slices',
                'Exercise: fixing borrow checker errors on purpose',
            ],
        },
        {
            title: 'Structs & Enums',
            description: 'Model your domain with data-carrying types.',
            lessons: [
                'Defining structs',
                'Methods and impl blocks',
                'Associated functions (String::new style)',
                'Tuple structs and unit structs',
                'Enums with data',
                'Option<T>: no more null',
                'match patterns in depth',
                'Exercise: modeling shapes and messages',
            ],
        },
        {
            title: 'Error Handling',
            description: 'Recoverable and unrecoverable errors, the Rust way.',
            lessons: [
                'panic! and unrecoverable errors',
                'Result<T, E>',
                'Propagating errors with ?',
                'unwrap and expect (and when they are fine)',
                'Custom error types',
                'Error crates: thiserror and anyhow overview',
                'When to panic vs return Result',
            ],
        },
        {
            title: 'Collections & Strings',
            description: 'Vectors, hash maps, and the truth about UTF-8 strings.',
            lessons: [
                'Vec<T>: creating, updating, reading',
                'Iterating vectors',
                'String vs &str',
                'UTF-8: bytes, chars, and grapheme reality',
                'Concatenation and formatting',
                'HashMap<K, V>',
                'The entry API',
                'Exercise: word frequency with HashMap',
            ],
        },
        {
            title: 'Generics, Traits & Lifetimes',
            description: 'Rust’s abstraction trio — powerful and fully compile-time.',
            lessons: [
                'Generic functions and structs',
                'Defining traits',
                'Implementing traits and default methods',
                'Trait bounds and where clauses',
                'derive macros (Debug, Clone, PartialEq)',
                'Trait objects (dyn) vs generics',
                'Lifetimes: what they actually mean',
                'Lifetime annotations in functions and structs',
                'The static lifetime',
            ],
        },
        {
            title: 'Closures & Iterators',
            description: 'Functional Rust with zero runtime cost.',
            lessons: [
                'Closure syntax and capturing',
                'Fn, FnMut, FnOnce',
                'The Iterator trait',
                'Adapters: map, filter, zip, enumerate',
                'collect and turbofish',
                'Consuming adapters: sum, fold, count',
                'Writing your own iterator',
                'Iterators vs loops: performance',
            ],
        },
        {
            title: 'Smart Pointers & Interior Mutability',
            description: 'Beyond references: heap allocation and shared ownership.',
            lessons: [
                'Box<T>: heap allocation',
                'Deref and Drop traits',
                'Rc<T>: reference counting',
                'RefCell<T> and interior mutability',
                'Combining Rc and RefCell',
                'Reference cycles and Weak<T>',
            ],
        },
        {
            title: 'Concurrency',
            description: 'Fearless concurrency: data races are compile errors.',
            lessons: [
                'Spawning threads',
                'move closures with threads',
                'Channels (mpsc)',
                'Shared state: Mutex<T> and Arc<T>',
                'Send and Sync traits',
                'async/await overview and tokio intro',
            ],
        },
        {
            title: 'Project Organization & Tooling',
            description: 'Modules, tests, docs — professional Rust projects.',
            lessons: [
                'Modules, paths, and visibility (pub)',
                'Splitting into files and directories',
                'Workspaces',
                'Unit tests and integration tests',
                'Documentation with rustdoc and doc tests',
                'clippy and rustfmt',
                'Publishing a crate',
            ],
        },
        {
            title: 'Capstone Project',
            description: 'A complete CLI tool with tests and proper error handling.',
            lessons: [
                'Scoping: a grep-style search tool (or task manager)',
                'Parsing arguments (clap)',
                'Core logic with iterators',
                'Error handling with Result end to end',
                'Reading environment and files',
                'Test suite and refactor',
                'Release build and distribution',
            ],
        },
    ],
};
