import { CourseDefinition } from '../types';

export const sql: CourseDefinition = {
    id: 'sql',
    title: 'Complete SQL Mastery',
    tagline: 'Query, design, and optimize relational databases with confidence.',
    level: 'Beginner → Advanced',
    hours: 20,
    accent: '#E38C00',
    badge: 'SQL',
    modules: [
        {
            title: 'Getting Started',
            description: 'Databases, the relational model, and your practice environment.',
            lessons: [
                'What are databases and DBMSs',
                'Relational vs NoSQL (the big picture)',
                'The relational model: tables, rows, keys',
                'Installing MySQL (or using SQLite)',
                'Loading the sample database',
                'Your first query',
            ],
        },
        {
            title: 'Retrieving Data From a Single Table',
            description: 'SELECT: the statement you will write for the rest of your life.',
            lessons: [
                'The SELECT clause and column expressions',
                'Aliases with AS',
                'The WHERE clause',
                'AND, OR, NOT',
                'The IN operator',
                'BETWEEN',
                'LIKE and pattern matching',
                'REGEXP',
                'IS NULL',
                'ORDER BY',
                'LIMIT (and OFFSET)',
                'Exercises: querying the customers table',
            ],
        },
        {
            title: 'Retrieving Data From Multiple Tables',
            description: 'Joins — the superpower of relational databases.',
            lessons: [
                'Inner joins',
                'Joining across databases',
                'Self joins',
                'Joining more than two tables',
                'Compound join conditions',
                'Implicit join syntax (and why to avoid it)',
                'Outer joins (LEFT / RIGHT)',
                'Outer joins between multiple tables',
                'Self outer joins',
                'The USING clause',
                'Natural and cross joins',
                'UNION',
            ],
        },
        {
            title: 'Inserting, Updating & Deleting Data',
            description: 'Writing data — safely.',
            lessons: [
                'Column attributes (NOT NULL, defaults, auto increment)',
                'Inserting a single row',
                'Inserting multiple rows',
                'Inserting hierarchical rows',
                'Creating a copy of a table',
                'Updating a single row',
                'Updating multiple rows',
                'Using subqueries in updates',
                'Deleting rows (and the WHERE you must not forget)',
            ],
        },
        {
            title: 'Summarizing Data',
            description: 'Aggregate your way to insights.',
            lessons: [
                'Aggregate functions: SUM, AVG, MIN, MAX, COUNT',
                'The GROUP BY clause',
                'The HAVING clause (vs WHERE)',
                'GROUP BY with multiple columns',
                'ROLLUP',
                'Exercise: sales summary report',
            ],
        },
        {
            title: 'Writing Complex Queries',
            description: 'Subqueries in all their forms.',
            lessons: [
                'Subqueries in WHERE',
                'The IN operator with subqueries',
                'Subqueries vs joins',
                'The ALL keyword',
                'The ANY keyword',
                'Correlated subqueries',
                'The EXISTS operator',
                'Subqueries in the SELECT clause',
                'Subqueries in the FROM clause',
            ],
        },
        {
            title: 'Essential Functions',
            description: 'The built-in functions used in every real query.',
            lessons: [
                'Numeric functions (ROUND, CEILING, FLOOR, ABS)',
                'String functions (CONCAT, SUBSTRING, TRIM, REPLACE)',
                'Date and time functions',
                'Formatting dates',
                'Calculating date differences',
                'IFNULL and COALESCE',
                'The IF function',
                'CASE expressions',
            ],
        },
        {
            title: 'Views',
            description: 'Reusable, simplified windows onto your data.',
            lessons: [
                'Creating views',
                'Altering and dropping views',
                'Updatable views',
                'WITH CHECK OPTION',
                'Benefits (and limits) of views',
            ],
        },
        {
            title: 'Stored Procedures & Functions',
            description: 'Put logic in the database — when it belongs there.',
            lessons: [
                'What stored procedures are and why',
                'Creating a stored procedure',
                'Parameters',
                'Default parameter values',
                'Validating parameters and raising errors',
                'Output parameters',
                'Variables',
                'User-defined functions',
                'Conventions and when to avoid stored logic',
            ],
        },
        {
            title: 'Triggers & Events',
            description: 'Reacting to data changes automatically.',
            lessons: [
                'Creating triggers',
                'Viewing and dropping triggers',
                'Using triggers for auditing',
                'Events (scheduled tasks)',
                'Altering triggers and events',
            ],
        },
        {
            title: 'Transactions & Concurrency',
            description: 'Keep data correct when many users write at once.',
            lessons: [
                'What transactions are',
                'ACID properties',
                'START TRANSACTION, COMMIT, ROLLBACK',
                'Concurrency problems: dirty reads',
                'Lost updates and non-repeating reads',
                'Phantom reads',
                'Isolation levels',
                'Deadlocks and how to reduce them',
            ],
        },
        {
            title: 'Data Types & Database Design',
            description: 'Model data properly: types, ERDs, and normalization.',
            lessons: [
                'String types',
                'Integer and fixed-point (DECIMAL) types',
                'Boolean, enum, and set types',
                'Date/time types',
                'BLOB and JSON types',
                'Data modelling and ERDs',
                'Primary keys and foreign keys',
                'Normalization: 1NF, 2NF, 3NF',
                'Forward and reverse engineering a schema',
                'Project: design a school database',
            ],
        },
        {
            title: 'Indexing for High Performance',
            description: 'Make slow queries fast — and know the cost.',
            lessons: [
                'How indexes work (B-trees)',
                'Creating indexes',
                'Viewing indexes',
                'Prefix indexes',
                'Composite indexes and column order',
                'Covering indexes',
                'When indexes are ignored',
                'The cost of indexes on writes',
            ],
        },
        {
            title: 'Securing the Database',
            description: 'Users, privileges, and least-privilege access.',
            lessons: [
                'Creating users',
                'Viewing and dropping users',
                'Changing passwords',
                'Granting privileges',
                'Viewing and revoking privileges',
                'Least privilege in practice',
            ],
        },
    ],
};
