import { CourseDefinition } from '../types';

export const swift: CourseDefinition = {
    id: 'swift',
    title: 'Swift Mastery',
    tagline: 'Apple’s modern language — optionals, protocols, and your first SwiftUI app.',
    level: 'Beginner → Advanced',
    hours: 30,
    accent: '#F05138',
    badge: 'SW',
    modules: [
        {
            title: 'Getting Started',
            description: 'Swift, Xcode, and Playgrounds — your lab for learning.',
            lessons: [
                'What is Swift and the Apple ecosystem',
                'Installing Xcode (or Swift on Linux/Windows)',
                'Playgrounds: interactive Swift',
                'Your first program',
                'Constants (let) and variables (var)',
                'print and string interpolation',
            ],
        },
        {
            title: 'Types & Operators',
            description: 'Swift’s strict but inferred type system.',
            lessons: [
                'Type inference and type annotations',
                'Int, Double, Bool, String',
                'Numeric literals and conversions',
                'Tuples',
                'Arithmetic and compound assignment',
                'Comparison and logical operators',
                'Range operators',
                'typealias',
            ],
        },
        {
            title: 'Control Flow',
            description: 'Branching with Swift’s powerful pattern matching.',
            lessons: [
                'if / else',
                'switch and pattern matching',
                'where clauses in switch',
                'for-in loops',
                'while and repeat-while',
                'guard statements (early exit)',
                'Labeled statements',
                'Exercise: grading engine with switch',
            ],
        },
        {
            title: 'Optionals',
            description: 'Swift’s signature feature: nil handled safely.',
            lessons: [
                'Why optionals exist',
                'Declaring optionals',
                'Force unwrapping (and its dangers)',
                'Optional binding: if let',
                'guard let',
                'Nil-coalescing operator (??)',
                'Optional chaining',
                'Implicitly unwrapped optionals',
                'Exercise: safe user-input parser',
            ],
        },
        {
            title: 'Collections',
            description: 'Arrays, sets, and dictionaries with value semantics.',
            lessons: [
                'Arrays: creating and modifying',
                'Iterating with indices and enumerated()',
                'Sets and set algebra',
                'Dictionaries',
                'Value semantics and copy-on-write',
                'Common operations: sorted, contains, first(where:)',
            ],
        },
        {
            title: 'Functions & Closures',
            description: 'First-class functions and Swift’s closure syntax.',
            lessons: [
                'Defining functions',
                'Argument labels and parameter names',
                'Default, variadic, and inout parameters',
                'Functions as types',
                'Closure expressions',
                'Trailing closure syntax',
                'Capturing values',
                'Escaping closures',
                'map, filter, reduce, compactMap',
            ],
        },
        {
            title: 'Structs & Classes',
            description: 'Value vs reference types — the decision at the heart of Swift design.',
            lessons: [
                'Structs vs classes: when to use which',
                'Stored and computed properties',
                'Lazy properties',
                'Property observers (willSet / didSet)',
                'Methods and mutating methods',
                'Initializers and memberwise init',
                'Failable initializers',
                'Deinitializers',
                'Identity (===) vs equality (==)',
            ],
        },
        {
            title: 'Enums & Pattern Matching',
            description: 'Enums with associated values: modeling states precisely.',
            lessons: [
                'Defining enums',
                'Raw values',
                'Associated values',
                'Matching enums in switch',
                'CaseIterable',
                'Recursive enums (indirect)',
                'Exercise: modeling a network state machine',
            ],
        },
        {
            title: 'Protocols & Extensions',
            description: 'Protocol-oriented programming — the Swift way.',
            lessons: [
                'Protocol syntax and conformance',
                'Protocols with properties and methods',
                'Protocol inheritance and composition',
                'Extensions',
                'Protocol extensions and default implementations',
                'Equatable, Hashable, Comparable',
                'Codable: encoding and decoding JSON',
                'Protocol-oriented design vs class inheritance',
            ],
        },
        {
            title: 'Generics & Error Handling',
            description: 'Flexible code and honest failure handling.',
            lessons: [
                'Generic functions and types',
                'Type constraints',
                'Associated types in protocols',
                'Opaque types (some)',
                'Throwing functions and do-try-catch',
                'try? and try!',
                'The Result type',
                'defer',
            ],
        },
        {
            title: 'Memory & Concurrency',
            description: 'ARC, retain cycles, and modern Swift concurrency.',
            lessons: [
                'Automatic Reference Counting (ARC)',
                'Strong, weak, and unowned references',
                'Retain cycles and closures ([weak self])',
                'async / await',
                'Tasks and task groups',
                'Actors',
                'MainActor and UI updates',
            ],
        },
        {
            title: 'SwiftUI First Steps + Capstone',
            description: 'Build a real iOS app screen by screen.',
            lessons: [
                'SwiftUI: views and modifiers',
                'State and Binding',
                'Lists and navigation',
                'Forms and user input',
                'Observable objects and app state',
                'Capstone: to-do or weather app — design',
                'Capstone: build the views and logic',
                'Capstone: persistence, polish, and review',
            ],
        },
    ],
};
