import { Course } from '../types';

export const typescript: Course = {
    id: 'typescript',
    title: 'TypeScript Mastery',
    tagline: 'Level up your JavaScript with static types, generics, and pro tooling.',
    level: 'Intermediate (JavaScript required)',
    hours: 20,
    accent: '#3178C6',
    badge: 'TS',
    modules: [
        {
            title: 'Getting Started',
            description: 'Why TypeScript exists and how to set up the compiler properly.',
            lessons: [
                'What is TypeScript and why use it',
                'Installing the TypeScript compiler',
                'Your first TypeScript program',
                'Configuring tsconfig.json (the options that matter)',
                'Compiling and running',
                'Debugging with source maps',
            ],
        },
        {
            title: 'Fundamentals',
            description: 'The built-in types and how annotation and inference work together.',
            lessons: [
                'Type annotations vs type inference',
                'Built-in types: number, string, boolean',
                'The any type (and why to avoid it)',
                'Arrays',
                'Tuples',
                'Enums (and const enums)',
                'Typing functions: parameters and return types',
                'Typing objects',
            ],
        },
        {
            title: 'Advanced Types',
            description: 'Unions, intersections, literals — the types that model real data.',
            lessons: [
                'Type aliases',
                'Union types',
                'Intersection types',
                'Literal types',
                'Nullable types and strictNullChecks',
                'Optional chaining and nullish coalescing with types',
                'Type assertions (as)',
                'unknown vs any',
                'The never type',
            ],
        },
        {
            title: 'Type Narrowing',
            description: 'Teach the compiler what you already know about your values.',
            lessons: [
                'typeof and truthiness narrowing',
                'instanceof and in narrowing',
                'Equality narrowing',
                'Discriminated unions',
                'Type predicates (is)',
                'Exhaustiveness checking with never',
            ],
        },
        {
            title: 'Object-Oriented TypeScript',
            description: 'Classes and interfaces with full compile-time safety.',
            lessons: [
                'Classes and constructors',
                'Access modifiers: public, private, protected',
                'Parameter properties',
                'Readonly and optional properties',
                'Getters and setters',
                'Index signatures',
                'Static members',
                'Inheritance and method overriding',
                'Polymorphism and the open-closed principle',
                'Abstract classes',
                'Interfaces vs type aliases',
                'Implementing interfaces',
            ],
        },
        {
            title: 'Generics',
            description: 'Write flexible, reusable code without giving up type safety.',
            lessons: [
                'Why generics exist',
                'Generic functions',
                'Generic classes',
                'Generic interfaces',
                'Generic constraints (extends)',
                'Extending generic classes',
                'The keyof operator',
                'Mapped types',
            ],
        },
        {
            title: 'Utility & Conditional Types',
            description: 'The type-level toolbox: transform types instead of rewriting them.',
            lessons: [
                'Partial, Required, and Readonly',
                'Pick, Omit, and Record',
                'ReturnType, Parameters, and Awaited',
                'Template literal types',
                'Conditional types',
                'infer',
            ],
        },
        {
            title: 'Decorators',
            description: 'Meta-programming for classes — the feature behind Angular and NestJS.',
            lessons: [
                'What decorators are and enabling them',
                'Class decorators',
                'Method decorators',
                'Accessor and property decorators',
                'Parameter decorators',
                'Decorator factories and composition',
            ],
        },
        {
            title: 'Modules & Project Structure',
            description: 'Organizing real TypeScript codebases.',
            lessons: [
                'Exporting and importing',
                'Default exports and re-exports',
                'Module resolution explained',
                'Namespaces (and why modules won)',
                'Path aliases',
                'Declaration merging basics',
            ],
        },
        {
            title: 'Integrating with JavaScript',
            description: 'Adopt TypeScript gradually in existing JS projects.',
            lessons: [
                'Including JS code with allowJs',
                'Type checking JS with checkJs and @ts-check',
                'Describing types with JSDoc',
                'Declaration files (.d.ts)',
                'Using @types / DefinitelyTyped packages',
                'Migration strategy for a real project',
            ],
        },
        {
            title: 'Tooling & Quality',
            description: 'The professional TypeScript toolchain.',
            lessons: [
                'ESLint with typescript-eslint',
                'Formatting with Prettier',
                'Running TS directly (tsx, ts-node)',
                'Building with Vite / esbuild',
                'Testing typed code (Vitest / Jest)',
                'Publishing a typed npm package',
            ],
        },
        {
            title: 'TypeScript in the Real World + Capstone',
            description: 'Framework patterns, then build a fully typed project.',
            lessons: [
                'Typing React components and hooks',
                'Typing Node.js / Express APIs',
                'Zod and runtime validation meets static types',
                'Capstone: design a typed REST API',
                'Capstone: shared types between client and server',
                'Capstone: tests, build, and ship',
            ],
        },
    ],
};
