import { CourseDefinition } from '../types';

export const vue: CourseDefinition = {
    id: 'vue',
    title: 'Vue.js Mastery',
    tagline: 'The approachable, batteries-included framework — from directives to Pinia.',
    level: 'Intermediate (JavaScript required)',
    hours: 24,
    accent: '#42B883',
    badge: 'V',
    requires: ['node'],
    category: 'framework',
    stack: 'JavaScript',
    modules: [
        {
            title: 'Getting Started',
            description: 'Vue’s philosophy and your first single-file component.',
            lessons: [
                'What is Vue and where it shines',
                'Trying Vue via CDN vs a real project',
                'Scaffolding with create-vue (Vite)',
                'Single-File Components (.vue) anatomy',
                'Vue DevTools',
                'Options API vs Composition API (course uses Composition)',
            ],
        },
        {
            title: 'Template Syntax & Reactivity',
            description: 'Vue’s reactive core: refs, computed, and watchers.',
            lessons: [
                'Text interpolation and expressions',
                'ref() and reactive()',
                'How Vue reactivity actually works',
                'computed properties',
                'watch and watchEffect',
                'Template refs',
                'Exercise: live currency converter',
            ],
        },
        {
            title: 'Rendering & Directives',
            description: 'Conditionals, lists, and dynamic styling.',
            lessons: [
                'v-if vs v-show',
                'v-for and the key attribute',
                'v-for with objects and ranges',
                'Class bindings',
                'Style bindings',
                'v-html (and its XSS caveat)',
            ],
        },
        {
            title: 'Events & Forms',
            description: 'User input, two-way binding, and modifiers.',
            lessons: [
                'v-on and event handlers',
                'Event modifiers (.prevent, .stop, .once)',
                'Key modifiers',
                'v-model on inputs, checkboxes, selects',
                'v-model modifiers (.number, .trim, .lazy)',
                'Exercise: multi-field form with validation',
            ],
        },
        {
            title: 'Components',
            description: 'Composing UIs: props down, events up, slots for everything else.',
            lessons: [
                'Defining and registering components',
                'Props and prop validation',
                'Emitting events (defineEmits)',
                'v-model on components',
                'Slots and named slots',
                'Scoped slots',
                'provide / inject',
                'Dynamic components and KeepAlive',
                'Lifecycle hooks',
            ],
        },
        {
            title: 'Composition API in Depth',
            description: 'Organize logic into reusable composables.',
            lessons: [
                'script setup deep dive',
                'Writing composables (useX functions)',
                'Composable patterns: state, events, cleanup',
                'VueUse: the composable standard library',
                'Comparing with the Options API (reading old code)',
            ],
        },
        {
            title: 'Routing with Vue Router',
            description: 'Client-side navigation for real apps.',
            lessons: [
                'Setting up Vue Router',
                'Routes, RouterLink, RouterView',
                'Route params and query',
                'Nested routes and layouts',
                'Programmatic navigation',
                'Navigation guards (auth)',
                'Lazy-loading routes',
            ],
        },
        {
            title: 'State Management with Pinia',
            description: 'Global state that stays debuggable.',
            lessons: [
                'Why a store (and when not to)',
                'Defining stores',
                'State, getters, actions',
                'Using stores in components',
                'Persisting store state',
                'Exercise: cart store for a shop',
            ],
        },
        {
            title: 'Data Fetching & Async Patterns',
            description: 'Server data with loading, errors, and caching.',
            lessons: [
                'Fetching in composables',
                'Loading and error states',
                'TanStack Query for Vue',
                'Suspense (experimental) overview',
                'Optimistic UI',
            ],
        },
        {
            title: 'TypeScript & Testing',
            description: 'Typed components and tests that catch regressions.',
            lessons: [
                'TypeScript in SFCs (typed props/emits)',
                'Typing composables and stores',
                'Vitest + Vue Test Utils',
                'Testing components like a user',
                'Mocking the router and stores',
            ],
        },
        {
            title: 'Capstone Project (+ Nuxt Preview)',
            description: 'Build and ship a complete Vue app, then peek at Nuxt.',
            lessons: [
                'Nuxt: what SSR/file routing adds',
                'Capstone scoping: recipe manager or dashboard',
                'Routing and layout skeleton',
                'Pinia data layer + API integration',
                'Forms and validation',
                'Polish and deploy',
            ],
        },
    ],
};
